### ISSUE TITLE
bug: Character input to search exiting search

### ISSUE THREAD

**Issue by Whompratt** [LazyVim/LazyVim#2335] opened 2024-01-10 16:27 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.0

### Describe the bug

With a buffer open, input '/' to enter search, then inputting certain character combinations exits the search and goes back to Normal mode.
Is search exited once no matches are found?

### Steps To Reproduce

1. With a buffer open, use '/' to enter search
2. Type 'carrier'
3. Search mode exists after 'ca', with the remaining characters being treated as though they were input in normal mode.

### Expected Behavior

Inputting keys '/carrier' would result in a search for 'carrier', with or without results.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-01-10 16:31
Duplicate of #1862. Please do some search before creating a new issue. And kindly close this issue.

**Closed** 2024-01-21 19:47 UTC
Labels: bug
