### ISSUE TITLE
bug: after LspRestart nvim spams method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by Nybkox** [LazyVim/LazyVim#3246] opened 2024-05-19 20:26 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 14.1

### Describe the bug

1. After deleting several buffers, LspRestart causes nvim to spam `method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer`.

2. Turning on vim-illuminate extra does not disable native LSP highlighting.
Only manually adding 
```lua
document_highlight = {
      enabled = false,
}
```
into lsp config opts fixes the issue.

Seems to be related to https://github.com/LazyVim/LazyVim/commit/cc99b219ded16ec60120698d6e8f453c2f37132c.

<img width="1047" alt="image" src="https://github.com/LazyVim/LazyVim/assets/25556202/0a0bae23-4994-46d7-b9e3-e2895f027887">

### Steps To Reproduce

1. open 5-10 buffers (tested on TS project)
2. close several buffers
3. :LspRestart
4. move cursor

### Expected Behavior

no error messages appears

**Comment by dpetka2001** [comment] 2024-05-19 22:04
Cannot reproduce with Lua LSP. 

[Screencast 2024-05-20 01:03:43.webm](https://github.com/LazyVim/LazyVim/assets/12776461/ad0665f4-49c6-4900-b21a-b5d157eb5d01)

Maybe it has something to do with `tsserver`?

**Comment by folke** [comment] 2024-05-19 22:09
This should be fixed now.
The document highlight stuff in LazyVim also didn't work for tsserver or any other lsp server that advertises the capability dynamically. Should work fine now.

The errors also cant happen since we now remove the handlers on LspDetach

**Comment by hopezh** [comment] 2024-05-23 07:08
I had the same error `method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer` recently after I update my `neovim` and `lazyvim`, but only for `qmd` file, a kind of `markdown` file type, as indicated [here](https://github.com/quarto-dev/quarto-nvim/issues/125?notification_referrer_id=NT_kwDOAWWaIrQxMDc1MTk4Njc3NjoyMzQzNTgxMA). 

My fork of lazyvim config is [here](https://github.com/hopezh/oatvim07).

Following [suggestion](https://www.reddit.com/r/neovim/comments/qhh4qr/nvimlspconfig_error_method_textdocumentcodeaction/) of neovim users, I used autocmd CursorHold command, and the output is:

![332465789-47eae7b9-86b5-4cf0-bc63-db9589922c10](https://github.com/LazyVim/LazyVim/assets/23435810/2b9be314-1680-422b-ac5d-21fb8b5201c5)

And this is where `textDocument/documentHighlight` is mentioned in `lazyvim`, but I don't know whether it is related to this error. 

![image](https://github.com/LazyVim/LazyVim/assets/23435810/8496065d-8fa1-438b-8f52-f46b851a9c44)

Would appreciate advice on the source of such error and how to solve it. 

Thanks.

**Comment by folke** [comment] 2024-05-23 15:20
@hopezh can you please update LAzyVim and see if it still happens?
Shouldn't be possible, since we only start document highlights when we're certain an attached lsp server has support.

**Comment by folke** [comment] 2024-05-23 15:22
I can reproduce it using your config. Will check what's happening here

**Comment by folke** [comment] 2024-05-23 15:39
@hopezh fixed on main. Will make a new release in a bit

**Closed** 2024-05-23 15:39 UTC
Labels: bug

**Comment by hopezh** [comment] 2024-05-24 02:40
> @hopezh fixed on main. Will make a new release in a bit

Thank you very much, @folke !!!

Yes, I updated `lazyvim` to `v11.6.1`,  and no such issue anymore.

https://github.com/LazyVim/LazyVim/assets/23435810/46b9fd3a-cc2e-4321-a2ca-eb5d0f94e7ef

**Comment by folke** [comment] 2024-05-24 07:20
Great!

**Comment by francoisrob** [comment] 2024-05-27 09:57
Still getting the textDocument/documentHighlight error on Lazyvim 11.8.0:
![image](https://github.com/LazyVim/LazyVim/assets/67432234/65563d80-9b14-4974-a3c8-4c782a5e2eb1)

NVIM v0.10.0

To reproduce I lspRestart to show the message.
It occasionally also shows;
![image](https://github.com/LazyVim/LazyVim/assets/67432234/83d12ccf-131f-4c4d-b50f-083c61183dd4)

My lspConfig below:
```
-- add tsserver and setup with typescript.nvim instead of lspconfig
local util = require "lspconfig.util"
return {
  "neovim/nvim-lspconfig",
  dependencies = {
    {
      "pmizio/typescript-tools.nvim",
      dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
    },
  },
  ---@class PluginLspOpts
  opts = {
    ---@type lspconfig.options
    servers = {
    ...
      tsserver = {
        filetypes = { "typescript" },
        root_dir = util.root_pattern("tsconfig.json"),
      },
      ...
    },
   ...
    ---@type table<string, fun(server:string, opts:_.lspconfig.options):boolean?>
    setup = {
      tsserver = function(_, opts)
        require("typescript-tools").setup({ server = opts })
        return true
      end,
      -- ["*"] = function(server, opts) end,
    },
  },
}
```

**Comment by folke** [comment] 2024-05-27 11:24
Do you still get the error after restart? Or only during?

**Comment by Nybkox** [comment] 2024-05-27 11:27
@folke, 
> Do you still get the error after restart? Or only during?
for me, it happens only once after calling :LspRestart.

**Comment by dpetka2001** [comment] 2024-05-27 11:54
I don't think you're setting up `typescript-tools` correctly. You don't need to specify `tsserver` at all in `nvim-lspconfig` as they also mention in their repo. I have it set up like [this](https://github.com/dpetka2001/dotfiles/blob/4e9b79b86641c7d557c3749ffde2975e30c57099/dot_config/nvim/lua/plugins/extras/lang/web_dev.lua#L90-L105) and I don't get the error about `documentHighlight`. I occasionally do get the error 
```
LSP[typescript-tools]: Error ON_EXIT_CALLBACK_ERROR: ".../nightly/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:394: attempt to index local 'client' (a nil value)"
```
after `LspRestart`.

**Comment by folke** [comment] 2024-05-27 11:56
That ON_EXIT error is probably not related to document highlights?

**Comment by dpetka2001** [comment] 2024-05-27 12:05
I don't think it is. I still get document highlights correctly. And I didn't get the error about `documentHighlight is not supported`.

**Comment by Nybkox** [comment] 2024-05-27 15:47
@dpetka2001, for me it happens w/o typescript-tools as well.

my whole lsp config:
```
return {
  "neovim/nvim-lspconfig",
  opts = {
    inlay_hints = {
      enabled = false,
    },
  },
  keys = {
    {
      "<leader>ci",
      function()
        vim.lsp.buf.code_action({
          apply = true,
          context = {
            only = { "source.addMissingImports.ts" },
            diagnostics = {},
          },
        })
      end,
      desc = "Add Missing Imports",
    },
    {
      "<leader>cq",
      function()
        vim.lsp.buf.code_action({
          apply = true,
          context = {
            only = { "source.removeUnused.ts" },
            diagnostics = {},
          },
        })
      end,
      desc = "Fix All",
    },
  },
}

```

**Comment by Nybkox** [comment] 2024-05-27 15:55
1. git clone git@github.com:fellipeutaka/ultimate-app.git
2. pnpm i
3. open app.module.ts
4. move cursor to some variable and restart lsp
https://github.com/LazyVim/LazyVim/assets/25556202/504f9891-5c3b-4d8e-86ef-248329bea4f7

**Comment by folke** [comment] 2024-05-27 16:23
I just added an extra check for when the lsp server was stopped.

**Comment by Nybkox** [comment] 2024-05-27 16:29
@folke, appreciate your work man, the issue seems to be resolved. I can get some odd behavior if I spam `:LspRestart`, but it does not look like a real-world issue
