### ISSUE TITLE
bug: attempt to index local 'location' (a nil value)

### ISSUE THREAD

**Issue by cmarksabelita** [LazyVim/LazyVim#3157] opened 2024-05-14 07:36 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4

### Describe the bug

after updating plugins to latest 'gD' is no longer working and throwing this error.

here is the sample error that I am getting: 

Error executing vim.schedule lua callback: ...lar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp/util.lua:1120: attempt to index local 'location' (a nil value)

<img width="1121" alt="image" src="https://github.com/LazyVim/LazyVim/assets/148048097/c2703cb8-d9d0-4638-a846-a3bc6775d2a2">

### Steps To Reproduce

1. Update to latest plugins and latest nvim version
2. Test gd 
3. Throws error

<img width="1121" alt="image" src="https://github.com/LazyVim/LazyVim/assets/148048097/c2703cb8-d9d0-4638-a846-a3bc6775d2a2">

### Expected Behavior

should go to definition, but currently throwing error.

**Comment by msMatix** [comment] 2024-05-14 08:46
I have the same problem. I think it is a bug on telescope side. I fixed the telescope version to `0.1.6`. 
I hope the whole thing will be fixed soon

**Comment by vmarksabelita** [comment] 2024-05-14 09:13
thanks @msMatix I can confirm that the issue is on telescope side.
FYI temporary workaround 

https://github.com/nvim-telescope/telescope.nvim/issues/3100

**Comment by dpetka2001** [comment] 2024-05-14 09:30
I can confirm this is on telescope side and has to do with the recent changes to `jump to location`. If you don't want to change the source code inside the telescope plugin, another workaround you could use in your telescope spec is
```lua
  {
    "nvim-telescope/telescope.nvim",
    opts = {
      pickers = {
        lsp_definitions = {
          jump_type = "never",
        },
      },
    },
  },
```
That means that even if there's only one definition it will still open the Telescope picker and you have to choose the entry. At least until this gets fixed from Telescope's side.

**Comment by martinsjon** [comment] 2024-05-14 15:31
It seems they've reverted the commit. Just ran an update and it was fixed.

**Closed** 2024-05-14 19:50 UTC
Labels: bug
