### ISSUE TITLE
bug: vtsls randomly fails 

### ISSUE THREAD

**Issue by jpwallace22** [LazyVim/LazyVim#3465] opened 2024-06-05 16:20 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

12.0.0 8014306

### Operating system/version

MacOS 14.2

### Describe the bug

When using `vtsls` within a TypeScript codebase it will just randomly fail saying that: 
```bash
vtsls: -32603: Request textDocument/documentHighlight failed with message: Cannot find docuemnt file:///Users/path/to/document
```
And yes, the error has the word document misspelled. Also, this is on the `vtsls` repo: 
>Notice: Though the server is suitable for regular use scenarios at the current stage, there is no absolute guarantee for its robustness as the behavior of the wrapped VSCode extension doesn't always keep 100% clear to me. Users can view this server as a best-effort product but possbily not as reliable as other functionally identical alternatives.

Which does not instill confidence in the software. I love LazyVim and don't want to break away, but sadly this has been making me need to shut down and restart my `nvim` every 30 mins or so. 

### Steps To Reproduce

1. use vtsls for long enough

I have tried everything in my power to get a solid reproducible state, but I cant. I feel it happens most when Shifting through tabs, but can't prove it. 

### Expected Behavior

vtsls doesnt crash 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2024-06-05 16:26
I don't have any issues with vtsls. It's alot faster than tsserver.
Closing, since this is not a LazyVim issue. You should report it upstream

**Closed by folke** 2024-06-05 16:26 UTC
Labels: bug

**Comment by yangyuanxx** [comment] 2024-07-04 01:34
I can consistently reproduce this issue:

1. Open a .ts file;
2. Restart the LSP server (:LspRestart);
3. Close the .ts file that was just opened;
4. Reopen the same .ts file.

At this point, an error will occur: vtsls: -32603: Request textDocument/documentHighlight failed with message: Cannot find document file:///xxx

**Comment by DerTimonius** [comment] 2024-07-08 07:39
@yangyuanxx yup, having the same issue. I hope that there will be an easy option to opt out of vtsls, it doesn't work for me at all. had way fewer issues with tsserver and I'd be more than willing to sacrifice some speed to reduce the number of errors I get.

**Comment by igolkotek** [comment] 2024-07-11 08:02
Yes, this is so annoying message ((

At least :LspRestart helps to shut it up

**Comment by beyourselfm** [comment] 2024-07-12 08:20
> @yangyuanxx yup, having the same issue. I hope that there will be an easy option to opt out of vtsls, it doesn't work for me at all. had way fewer issues with tsserver and I'd be more than willing to sacrifice some speed to reduce the number of errors I get.

Me too.

**Comment by yioneko** [comment] 2024-07-12 09:47
Hey everyone, author of vtsls here. You can opt out of vtsls and use typescript-language-server instead by adding the following spec to your config (also ensure the typesciprt extra has been enabled):
```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      vtsls = {
        enabled = false,
      },
      tsserver = {
        enabled = true,
        settings = {
          typescript = {
            inlayHints = {
              includeInlayEnumMemberValueHints = true,
              includeInlayFunctionLikeReturnTypeHints = true,
              includeInlayFunctionParameterTypeHints = true,
              includeInlayParameterNameHints = "literals",
              includeInlayParameterNameHintsWhenArgumentMatchesName = false,
              includeInlayPropertyDeclarationTypeHints = true,
              includeInlayVariableTypeHints = false,
              includeInlayVariableTypeHintsWhenTypeMatchesName = false,
            },
          },
          completions = {
            completeFunctionCalls = true,
          },
        },
        keys = {
          {
            "<leader>co",
            function()
              vim.lsp.buf.code_action({
                apply = true,
                context = {
                  only = { "source.organizeImports.ts" },
                  diagnostics = {},
                },
              })
            end,
            desc = "Organize Imports",
          },
          {
            "<leader>cR",
            function()
              vim.lsp.buf.code_action({
                apply = true,
                context = {
                  only = { "source.removeUnused.ts" },
                  diagnostics = {},
                },
              })
            end,
            desc = "Remove Unused Imports",
          },
        },
      },
    },
    setup = {
      tsserver = function()
        return false
      end,
      vtsls = function()
        return true
      end,
    },
  },
}
```

But note that I don't think the error mentioned here
> Request textDocument/documentHighlight failed with message: Cannot find docuemnt file

is the server's fault. I can also reproduce it with typescript-language-server by following @yangyuanxx 's steps and I think the issue is on the client side. So good luck if it will work for you.

**Comment by igolkotek** [comment] 2024-07-12 13:39
Thank you, yioneko!

Initially I've reinstalled my Lazyvim, and bumped into the same issue.
But after your advice of exchanging `vtsls` with  `typescript-language-server` I got silence finally - new files created, no messages of files the server cannot find..

It works.

Thank you!

**Comment by igolkotek** [comment] 2024-07-12 17:44
Yes, yioneko,

Neovim 0.11.0 prerelease version seems to have no the issue.

Great and thanks!

**Comment by igolkotek** [comment] 2024-07-13 16:47
I've tested `neovim v.0.11.0` (the latest prerelease available) with `vtsls`.

I have to say, that there was no issue quite for a long, but after a while it returned: "a file not found".

So the reason is somewhere deeper than `ipairs`.

Now I'll return to  `typescript-language-server` and try more.

**Comment by jsantos42** [comment] 2024-07-28 14:35
I have a similar error:
```
vtsls: -32603: Request textDocument/inlayHint failed with message: <semantic> TypeScript Server Error (5.3.3)
```
Here is the log:
```
[START][2024-07-26 17:57:37] LSP logging initiated
[WARN][2024-07-26 17:57:37] ...lsp/handlers.lua:135	"The language server eslint triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2024-07-26 17:58:48] ...lsp/handlers.lua:623	"TSServer exited. Code: null. Signal: SIGTERM"
```
@yioneko  I tried your suggestion but now I have another error:
```
tsserver: 1: <semantic> TypeScript Server Error (5.3.3)
Debug Failure. Unexpected node.
Node PrefixUnaryExpression was unexpected.
Error: Debug Failure. Unexpected node.
Node PrefixUnaryExpression was unexpected.
```
Any suggestions?

**Comment by yioneko** [comment] 2024-07-28 14:56
@jsantos42 That error is fixed in TypeScript version 5.4. You can set `vtsls.autoUseWorkspaceTsdk = false` to use the bundled ts which is on the latest version. Also see https://github.com/yioneko/vtsls/issues/159#issuecomment-2159349677 if you just want to supress the error message while the inlay hint feature keeps not working.

**Comment by jsantos42** [comment] 2024-07-28 15:43
THANK YOU! After 3 days banging with my head on the wall, chatgpt, phind.com, etc, it turns out it was just updating the TS version 🙈 

Anyway, I updated the TS version on the project, but where can add that option `vtsls.autoUseWorkspaceTsdk = false`?
I apologise in advance if it's an obvious question, I'm a long time user of Jetbrains and moved to nvim last week.

I tried this in `.config/nvim/lua/config/options.lua`:
```
local vtls = require("vtls")
vtls.autoUseWorkspaceTsdk = false
```

and this in `.config/nvim/lua/plugins/lspconfig.lua`:
```
return {
  {
    "nvim-lspconfig",
    opts = {
      servers = {
        vtls = {
          settings = {
            autoUseWorkspaceTsdk = false,
          },
        },
      },
    },
  },
}
```

but none of them work

**Comment by yioneko** [comment] 2024-07-29 03:39
@jsantos42 Just search code `autoUseWorkspaceTsdk lang:lua` on github and it will give you examples in other users' configs. The trick is useful whenever you cound normt figure out how to configure something in nvim.

**Comment by zargham-leanix** [comment] 2024-07-29 15:47
@yioneko how do I check which version of typescript currently running ?

**Comment by yioneko** [comment] 2024-07-29 16:02
@zargham-leanix  https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/extras/lang/typescript.lua#L106-L112

There is a default mapping `<leader>cV` in lazyvim to view it.

**Comment by zargham-leanix** [comment] 2024-07-29 16:13
@yioneko  thank you for quick response. I am getting only workspace's version in the list even though I did set autoUseWorkspaceTsdk = false.
```
rreturn {
  "neovim/nvim-lspconfig",
    servers = {
      vtsls = {
        settings = {
          vtsls = {
            autoUseWorkspaceTsdk = false,
          },
        },
      },
    },
  },
}

```

**Comment by yioneko** [comment] 2024-07-30 03:01
@zargham-leanix Is the server installed through mason (lazyvim default)? What's output of `cd /path/to/mason_install_dir/packages/vtsls/node_modules/@vtsls/language-server/node_modules/@vtsls/language-service/dist && node -e "console.log(require.resolve('typescript'))"`? You can get `/path/to/mason_install_dir` by cmd `:lua =vim.env.MASON` in lazyvim. Also verify that if the bundled ts path `/path/to/mason_install_dir/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript` really exists.

**Comment by zargham-leanix** [comment] 2024-07-30 08:53
@yioneko  the output I get `...local/share/nvim/mason/packages/vtsls/node_modules/@vtsls/language-server/node_modules/typescript/lib/typescript.js`

and yes the path exists.

**Comment by yioneko** [comment] 2024-07-30 10:38
@zargham-leanix Could you provide a screenshot for the versions list with only the workspace version? It seems that the bundled version should be correctly resolved in your environment, and I tested that the server will exit immediately if the bundled version could not be resolved.
![image](https://github.com/user-attachments/assets/79c5ea65-2cbd-4539-a0b9-79b4b5548492)

**Comment by zargham-leanix** [comment] 2024-07-30 11:04
@yioneko  I get only 1 option, I have also tried re-installing vstls via mason.

<img width="970" alt="image" src="https://github.com/user-attachments/assets/fb3b8d5c-7511-4223-b718-2c0415c553ff">

**Comment by yioneko** [comment] 2024-07-30 12:56
@jsantos42 The `VS Code's Version` is the bundled ts version. The second missing option here is the workspace ts version. I think `autoUseWorkspaceTsdk = false` works fine here.

**Comment by zargham-leanix** [comment] 2024-07-30 14:54
@yioneko but I am still getting the error popups even on vscode's version, its really annoying.

**Comment by yioneko** [comment] 2024-07-30 16:12
@zargham-leanix What's your error message along with the stack trace? It might be different and still an issue on ts side.

**Comment by zargham-leanix** [comment] 2024-07-30 16:28
How do I get stack trace ? @yioneko  I only have the error message:

```
Error  18:26:50 notify.error vtsls: -32603: Request textDocument/documentHighlight failed with message: Cannot find document (file path)

```

**Comment by yioneko** [comment] 2024-07-30 16:45
@zargham-leanix Hmm that error is not related to the ts version used. For now I consider this an issue of nvim builtin lsp client and I could not investigate this unless reproduction steps provided. I'd suggest move to `typescript-language-server` as it seems to not have this issue as discussed in comments above though I'm not sure why because we have same code path to trigger this type of error.

**Comment by erdemozveren** [comment] 2024-09-21 10:33
I have this error too, i try everything (switching neovim versions,vtsls versions, even changed distro) but can not be able to find a solution except suppress errors.
Its happening in my js monorepo project when i switch to another sub package's file (only first time opening) and its only gone if i save file (sometimes saving it multiple times or switching insert mode before save do the trick), maybe this information will help you.

As a newbie in neovim i use this to supress errors.
Got it from https://github.com/yioneko/vtsls/issues/159#issuecomment-2159349677 and changed "find" parameter.
```
  {
    "folke/noice.nvim",
    event = "VeryLazy",
    opts = {
      routes = {
        {
          filter = {
            event = "notify",
            find = "Could not find source",
          },
          opts = { skip = true },
        },
      },
    },
  },
```
Even with suppressing errors i still have to do "saving" trick to get to show inline hints in buffer.
Hope it helps.

**Comment by trongbinh15** [comment] 2024-09-26 08:22
I believe this issue is caused by LazyVim's inability to handle inlay hints correctly from vtsls

**Comment by eric-2d** [comment] 2024-10-02 13:52
Issue still persists

Nvim v0.10.1
TypeScript 5.6.2
LazyVim 12.41.0
vtsls 0.2.6

**Comment by dpetka2001** [comment] 2024-10-02 14:12
This is the same error as this open issue at vtsls repo https://github.com/yioneko/vtsls/issues/159. You'll have to report your findings there and wait for it to be solved upstream.

**Comment by eric-2d** [comment] 2024-10-02 14:18
Thanks, I'll do that.

It just started happening to me, after randomly updating my modules.
