### ISSUE TITLE
bug: neo-tree delete confirmation prompt text is not visible

### ISSUE THREAD

**Issue by steve-down** [LazyVim/LazyVim#2527] opened 2024-02-09 01:43 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3474+gf5d59340a-Homebrew

### Operating system/version

MacOS 14.3

### Describe the bug

I have a vanilla LazyVim configuration, I'm primarily just changing the color theme to kanagawa, and pinning a major version for LuaSnip. When I attempt to delete a file, I get a confirmation popup, but there's no text other than "y/n":

![image](https://github.com/LazyVim/LazyVim/assets/99507170/9271f15a-c15f-43e9-9a10-f584f98bb41e)

This could be an issue in LazyVim, in neo-tree, it could be in my config (but again, it's so simple I'm doubtful about that). I've searched neo-tree's github for issues like this to no avail, and I may submit an issue over there in the hope that someone has seen this as well.

With the repro config below, what I'm noticing now is that the text is there, but it's black on nearly black, and the top border is still clipped:

![image](https://github.com/LazyVim/LazyVim/assets/99507170/6800fb8e-7b55-427f-91ec-b4921c2f85f5)

### Steps To Reproduce

1. Open nvim
2. Navigate to a file in the tree
3. Press `d`
4. Note the confirmation prompt clips the top border and the text is almost impossible to read and the popup top border is missing.

### Expected Behavior

Readable delete confirmation prompt appears

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
        vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
        "folke/tokyonight.nvim",
        "folke/LazyVim",
        -- enough plugins to load neo-tree
        { "nvim-lua/plenary.nvim", lazy = true },
        { "MunifTanjim/nui.nvim", lazy = true },
        -- this config comes from lua/lazyvim/plugins/editor.lua, I do not modify that in my configuration
        {
                "nvim-neo-tree/neo-tree.nvim",
                branch = "v3.x",
                cmd = "Neotree",
                keys = {
                        {
                                "<leader>fe",
                                function()
                                        require("neo-tree.command").execute({ toggle = true, dir = Util.root() })
                                end,
                                desc = "Explorer NeoTree (root dir)",
                        },
                        {
                                "<leader>fE",
                                function()
                                        require("neo-tree.command").execute({ toggle = true, dir = vim.loop.cwd() })
                                end,
                                desc = "Explorer NeoTree (cwd)",
                        },
                        { "<leader>e", "<leader>fe", desc = "Explorer NeoTree (root dir)", remap = true },
                        { "<leader>E", "<leader>fE", desc = "Explorer NeoTree (cwd)", remap = true },
                        {
                                "<leader>ge",
                                function()
                                        require("neo-tree.command").execute({ source = "git_status", toggle = true })
                                end,
                                desc = "Git explorer",
                        },
                        {
                                "<leader>be",
                                function()
                                        require("neo-tree.command").execute({ source = "buffers", toggle = true })
                                end,
                                desc = "Buffer explorer",
                        },
                },
                deactivate = function()
                        vim.cmd([[Neotree close]])
                end,
                init = function()
                        if vim.fn.argc(-1) == 1 then
                                local stat = vim.loop.fs_stat(vim.fn.argv(0))
                                if stat and stat.type == "directory" then
                                        require("neo-tree")
                                end
                        end
                end,
                opts = {
                        sources = { "filesystem", "buffers", "git_status", "document_symbols" },
                        open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
                        filesystem = {
                                bind_to_cwd = false,
                                follow_current_file = { enabled = true },
                                use_libuv_file_watcher = true,
                        },
                        window = {
                                mappings = {
                                        ["<space>"] = "none",
                                        ["Y"] = function(state)
                                                local node = state.tree:get_node()
                                                local path = node:get_id()
                                                vim.fn.setreg("+", path, "c")
                                        end,
                                },
                        },
                        default_component_configs = {
                                indent = {
                                        with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
                                        expander_collapsed = "",
                                        expander_expanded = "",
                                        expander_highlight = "NeoTreeExpander",
                                },
                        },
                },
                config = function(_, opts)
                        local function on_move(data)
                                Util.lsp.on_rename(data.source, data.destination)
                        end

                        local events = require("neo-tree.events")
                        opts.event_handlers = opts.event_handlers or {}
                        vim.list_extend(opts.event_handlers, {
                                { event = events.FILE_MOVED, handler = on_move },
                                { event = events.FILE_RENAMED, handler = on_move },
                        })
                        require("neo-tree").setup(opts)
                        vim.api.nvim_create_autocmd("TermClose", {
                                pattern = "*lazygit",
                                callback = function()
                                        if package.loaded["neo-tree.sources.git_status"] then
                                                require("neo-tree.sources.git_status").refresh()
                                        end
                                end,
                        })
                end,
        },
}
require("lazy").setup(plugins, {
        root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-02-09 08:29
Can't reproduce with a fresh LazyVim starter template.

**Comment by steve-down** [comment] 2024-02-09 13:25
Thanks for the response. So, if I started this all from scratch - no `~/.config/nvim` folder, and I've removed `~/.local/share/nvim` and `~/.local/state/nvim` and `~/.repro`, and I just run `nvim -u repro.lua .`, where do you suggest I look? I'm able to repro this with the repro lua pretty easily.

**Comment by dpetka2001** [comment] 2024-02-09 13:27
Can you try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Do you observe the same behavior with LazyVim defaults? Don't make any changes of your own.

For cleanup
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by steve-down** [comment] 2024-02-09 13:35
Oh, this is weird:

If I run exactly your steps, culminating in `NVIM_APPNAME=lazytest nvim`, I get

![image](https://github.com/LazyVim/LazyVim/assets/99507170/1f11355f-273d-41c5-9313-f24d3a3c40d1)


If I run these steps but provide a directory to open? As in `NVIM_APPNAME=lazytest nvim .` ? I get

![image](https://github.com/LazyVim/LazyVim/assets/99507170/b3a6fee5-5643-4c26-aef9-4a12b2691ea1)

**Comment by kobzar** [comment] 2024-02-09 13:59
Its look like some ptoblem with your color theme
So, the betrer way to test
Install fresh version of LazyVim
Check if all look nice, aplly your color theme - check again and back to default color theme to last check.

**Comment by dpetka2001** [comment] 2024-02-09 14:00
@steve-down 
Yes, I can reproduce when opening a directory. However I don't believe it's a LazyVim issue. In the repro file that you provided I commented out `folke/LazyVim`, so the only plugins that are installed then are `lazy.nvim, neo-tree.nvim, nui.nvim, plenary.nvim and tokyonight.nvim`. So, I was able to reproduce this without LazyVim by commenting it out in your `repro.lua`. 

That's why I believe it has something to do with `neo-tree` itself.

**Comment by steve-down** [comment] 2024-02-09 14:02
I agree - it's a strange edge condition, it would seem - no command-line == OK. file on the command line == OK. Directory on the command line == failed. 

Thanks so much for your help!

**Comment by dpetka2001** [comment] 2024-02-09 14:23
@steve-down 
Can you try the following? Instead of the `init` function that you use in your configuration, try to replace it with this
```lua
    init = function()
      vim.api.nvim_create_autocmd("BufEnter", {
        -- make a group to be able to delete it later
        group = vim.api.nvim_create_augroup("NeoTreeInit", { clear = true }),
        callback = function()
          local f = vim.fn.expand("%:p")
          if vim.fn.isdirectory(f) ~= 0 then
            vim.cmd("Neotree left dir=" .. f)
            -- neo-tree is loaded now, delete the init autocmd
            vim.api.nvim_clear_autocmds({ group = "NeoTreeInit" })
          end
        end,
      })
    end,
```
I'm not exactly sure why, but this seems to avoid the problem you're observing. I'm not sure why this happens and not familiar with `neo-tree`'s internals, so you might want to ask a question at their repo as what the correct approach should be.

**Comment by steve-down** [comment] 2024-02-09 14:29
Um, this is embarrassing... I think... you see the 0.10.0-dev version up there? 

```
brew remove neovim
brew install neovim
``` 

Problem appears solved against this repro.lua. Will also try your change to it. Thanks again!

**Comment by dpetka2001** [comment] 2024-02-09 14:34
What is the Neovim version you use that solved your issue?

**Comment by steve-down** [comment] 2024-02-09 14:40
The latest version available with Homebrew:

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```

**Comment by folke** [comment] 2024-03-22 09:26
If this is the case, then this should be fixed in neotree.
They should llisten for `ColorScheme` events and update their default colors accordingly.

**Closed by folke** 2024-03-22 09:26 UTC
Labels: bug
