### ISSUE TITLE
bug: Lsp doesnot work 

### ISSUE THREAD

**Issue by networkpankaj** [LazyVim/LazyVim#2474] opened 2024-01-31 17:59 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.95

### Operating system/version

windows

### Describe the bug

Lsp doesnot show any command like LspInfo and other command but Mason work properly

### Steps To Reproduce

Lsp doesnot show any commands while i type  

### Expected Behavior

Lsp doesnot work

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-01-31 18:08
If you type `:LspInfo`, does it pop up a floating window with information?

**Comment by networkpankaj** [comment] 2024-01-31 18:15
It shows not an editor command and it doesnot show any command

**Comment by networkpankaj** [comment] 2024-01-31 18:15
It works when i open file

**Comment by dpetka2001** [comment] 2024-01-31 18:22
Yes, the command `:LspInfo` only shows when you open a file. I still don't understand what your problem is. Can you clarify?

**Comment by networkpankaj** [comment] 2024-01-31 18:31
When i open nvim the dashboard , then i search for Lsp it doesnot show
anything

**Comment by dpetka2001** [comment] 2024-01-31 18:33
It's not supposed to show anything from dashboard, because no file has been opened yet. The LSP only attaches when you open a file in Neovim. This is expected behavior and not a bug. Kindly close the issue if that's your problem.

**Closed** 2024-01-31 18:37 UTC
Labels: bug

**Comment by networkpankaj** [comment] 2024-01-31 18:42
Thank you for the clarification.  I just want to ask one ques. When i open
the config the file in nvim and i search for LspInfo it shows me Ambigius
error ? Why

**Comment by dpetka2001** [comment] 2024-01-31 18:45
What do you mean? Which config file are you opening with Neovim? Can you be more specific? If you open a file from your terminal with `nvim init.lua` for example, then the command `LspInfo` should work.

**Comment by networkpankaj** [comment] 2024-02-01 04:41
It works!  But it show me Ambiguous use of user command ...

**Comment by networkpankaj** [comment] 2024-02-01 14:58
I want to ask you one thing related to web devlopment, in neovim how we
open browser in neovim when i run react project , i dont want to switch to
chrome and then come back can neovim open browser by splitting the window

**Comment by dpetka2001** [comment] 2024-02-01 15:44
No idea. I don't do web development, so am not familiar with the workflow.

**Comment by networkpankaj** [comment] 2024-02-02 10:14
Ok, thanks for the reply.
