### ISSUE TITLE
bug: Neo-tree window "jumps" when opening files 

### ISSUE THREAD

**Issue by ghidalgo93** [LazyVim/LazyVim#2131] opened 2023-12-04 23:21 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4 (and nightly, 0.10.0)

### Operating system/version

MacOS 14.1.1

### Describe the bug

For any directory/project in which the explorer items exceed the max line number (height of the explorer), if a file is opened below that max line number the file tree will jump to the top of the explorer.

This is the same issue that is described [in a nvimtree issue](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1025) however rolling back to stable nvim 0.9.4 or any of the other config options doesn't fix the issue. I also tried switching to nvim-tree and see the exact same behavior which makes me think this is a redraw issue related to lazyvim.

Behavior can be seen in this video (by https://github.com/georgeguimaraes in the neotree issue):

https://private-user-images.githubusercontent.com/2929/250934165-3fd2831d-b301-426e-874a-9490d7c0e80e.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzE3ODYsIm5iZiI6MTcwMTczMTQ4NiwicGF0aCI6Ii8yOTI5LzI1MDkzNDE2NS0zZmQyODMxZC1iMzAxLTQyNmUtODc0YS05NDkwZDdjMGU4MGUubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMjMxMTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE0MzlkM2MzN2MyMDgyZDAxODk4NDgwNGY1ZWQzNzdlZWYzYjU0NjA4ODMwZDVmNmZhZTBkNjYyYzk2YmY2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JIesEnDPAPtwwncAJas1W-ElK4rOj7gln2Jaw95jUI8

### Steps To Reproduce

1.     Open project
2.     Expand a bunch of directories to fill up the screen
3.     Open files that are close to the bottom of the neo-tree window
4.     See the explorer window jump to the top of the page 

### Expected Behavior

The explorer window stays centered on the currently opened file (or at least stays open with it _somewhere_ in the explorer buffer)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by ghidalgo93** [comment] 2023-12-04 23:25
I mentioned this above, for clarity however the config with neo-tree disabled and the addition of nvim-tree displays the same behavior, happy to post a video for that or any other info if that helps!

**Comment by dpetka2001** [comment] 2023-12-05 00:19
I'm not so sure this is a Lazyvim issue. The issue you mentioned, also redirects to another [issue](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/996), in which the user miversen33 has created a minimal repro file in this [comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/996#issuecomment-1823572908). I have tried that minimal repro and can reproduce the bug that you're observing. However, that minimal repro doesn't install LazyVim at all. Only `lazy.nvim`, `neo-tree` and some dependencies of `neo-tree`, including `nui.nvim`. The user miversen33 also mentions somewhere along that thread that his hunch is that `nui.nvim` is the culprit, although no explicit proof has been provided. Anyhow, it seems that this is not a LazyVim issue and you have better chance tracking that issue over at `neo-tree` repo in hopes it gets resolved.

**Comment by ghidalgo93** [comment] 2023-12-05 14:46
That was the rabbit hole I ended up going down as well, tracking this down in `neo-tree` issues and following the cascading issues. However, it's _only_ using LazyVim (both a minimal config above as well as my modified config) which I see this issue happening for _both_ `neo-tree` _and_ `nvim-tree` and for which the downgrade to a stable nvim doesn't fix the jumping behavior.

**Comment by dpetka2001** [comment] 2023-12-05 15:41
Have you tried the repro in this [comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/996#issuecomment-1823572908)? This isn't using LazyVim and I'm able to reproduce the issue.

**Comment by ghidalgo93** [comment] 2023-12-05 17:19
Ah yes, sorry I don't I'm being very clear - my apologies. The reason I came to this repo to submit this issue was because if I downgrade to nvim v0.9.4 or use `nvim-tree` _without_ LazyVim the issue does not exist, as soon as I use any LazyVim config the issue comes up regardless of nvim version or the two file explorer plugins I've tried (nvim-tree and neo-tree), so there seems (to me at least) to be something LazyVim related.

The collaborator in the comment you linked seems to think it might be `nui` related so I'm now curious if any default configs for nui in LazyVim might be causing the issue to persist where without LazyVim you can fix it by downgrading nvim or using another file explorer. I'm curious now and will try to mess around with the LazyVim `nui` configs to see if that yields anything...

**Comment by dpetka2001** [comment] 2023-12-05 17:41
I was testing on Neovim nightly in my previous post. I tried with Neovim 0.9.4 and with fresh LazyVim starter template and the issue cannot be reproduced. So, really I can't understand the steps to reproduce it. It seems to me that it is not LazyVim related from my tests and that it only occurs on Neovim nightly. I'm not that knowledgeable myself in programming to dig into code and understand what's wrong. I'm just testing things based on what you have described and what I've read in the other issues that you mentioned. For me on Neovim 0.9.4 and LazyVim default starter template without any customization I can't reproduce the issue. I can only reproduce it on nightly. But then again, when I try with the minimal config from the other issue that doesn't use LazyVim, I can still reproduce it. That's why I think it's not LazyVim related.

**Comment by ghidalgo93** [comment] 2023-12-05 18:35
Yeah, that makes sense! Now I'm just incredibly confused about how I can reproduce this in my stable nvim 🤔 but if you're able to get the explorer to behave correctly and not jump in stable then I completely agree with you, doesn't seem to be LazyVim related

**Comment by dpetka2001** [comment] 2023-12-05 18:41
Please try the following
```
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for installation of plugins to finish
4. Restart neovim with same command as step 3
```
Can you reproduce the `neo-tree` behavior with Neovim 0.9.4 with the above steps?

After you finish with your tests and want to remove the above installation, do
```
1. `rm -rf ~/.config/lazytest`
2. `rm -rf ~/.local/share/lazytest`
3. `rm -rf ~/.local/state/lazytest`
4. `rm -rf ~/.cache/lazytest`
```

**Comment by georgeguimaraes** [comment] 2023-12-06 14:39
Hi @ghidalgo93, I didn't reply to you on my original issue on neo-tree but I'm also a Lazyvim user. 

I'm using neovim 0.9.4 and also LazyVim and the issue is not present. 

Although I can reproduce it easily with neovim-head and the minimal repro.lua that the neotree maintainers suggest you to use. (that script does use https://github.com/folke/lazy.nvim, which is different from LazyVim. Maybe you're conflating the two?)

**Comment by dpetka2001** [comment] 2023-12-06 14:51
The minimal issue doesn't use Lazyvim. That suggests it's not Lazyvim related. I have tried the minimal repro and was able to reproduce it without Lazyvim installed. Therefore, i think it'd be best to close this and just track the aforementioned issue at `neo-tree` repo.

**Comment by georgeguimaraes** [comment] 2023-12-07 14:43
yeah, I forgot to add it explicitly in my reply but this is not a issue on LazyVim

**Comment by georgeguimaraes** [comment] 2023-12-29 03:44
This is now fixed upstream by https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1274

**Comment by dpetka2001** [comment] 2023-12-29 07:05
@ghidalgo93 Could you please close the issue since it has been fixed upstream and is not LazyVim related?

**Closed** 2024-01-21 19:46 UTC
Labels: bug
