### ISSUE TITLE
bug: Lazygit uses wrong width on first run

### ISSUE THREAD

**Issue by eifr** [LazyVim/LazyVim#4721] opened 2024-11-07 08:29 UTC
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

kde plasma 6.2.2

### Describe the bug

only on first run of lazygit, it uses wrong width and overflows. Second time I run it, it's ok.

https://github.com/user-attachments/assets/70894b94-0e16-47b3-8328-ce00657dcfb6

### Steps To Reproduce

1. enter nvim
2. enter lazygit 
3. lazygit overflow
4. quit lazygit
5. enter lazygit again
6. lazygit width is ok
7. if i quit nvim and enter again, it will overflow again on first lazygit

### Expected Behavior

lazygit show not overflow and use proper size

**Comment by dpetka2001** [comment] 2024-11-07 12:19
Maybe it's related to how KDE Plasma calculates the initial width of a window? Just a guess. I'm using Linux Mint Mate and Xfce and also Awesome window manager in Mate and Windows and can't reproduce this.

Does it happen when you have your window maximized? Or maybe only in a resized window?

**Comment by folke** [comment] 2024-11-07 12:46
I had that too, but the good news is that this seems fixed in snacks.nvim, which will be merged in LAzyVim soon...

**Comment by folke** [comment] 2024-11-07 14:57
Fixed on main

**Closed by folke** 2024-11-07 14:57 UTC
Labels: bug

**Comment by dpetka2001** [comment] 2024-11-07 15:23
I don't mean to nitpick, but I would like to understand what caused this and is not happening on `snacks` any more. Do you think it's Window manager related? Because I couldn't for the life of me reproduce it on the 3 different environments that I use.

**Comment by folke** [comment] 2024-11-07 15:50
The old lazygit used lazy's window class.
Snacks has its own new window class.

They're both very different, so there must've been a bug in lazy's that I fixed in snack
