### ISSUE TITLE
bug: LazyHealth E492

### ISSUE THREAD

**Issue by Freaksed** [LazyVim/LazyVim#2580] opened 2024-02-20 22:10 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Windows WSL2 Ubuntu

### Describe the bug

At first LazyHealth worked, I installed the things it mentioned were missing (ripgrep, fd, etc). Then it started reporting that LazyHealth was not an editor command

### Steps To Reproduce

Open nvim
Run LazyHealth

### Expected Behavior

It should run the LazyHealth utility

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-02-20 22:59
This is not a bug. `LazyHealth` is not incorporated in LazyVim stable yet, only if you follow HEAD you have this command. See #2400 which still hasn't been merged.

The reason this happens, is because `lazy.nvim` (the package manager), when it first installs LazyVim on initial install it clones the latest HEAD. But when you then check for updates, it will show you the latest stable release as an update and revert to the stable version. If you wish to have access to this command, you can follow HEAD by making the necessary changes in your personal configuration as stated in the [docs](https://www.lazyvim.org/configuration/lazy.nvim).

**Comment by Freaksed** [comment] 2024-02-20 23:58
AH ok thanks, yeah it would be nice if there was better messaging about this. Since when first running it does give you this tool and then it goes away.

**Comment by dpetka2001** [comment] 2024-02-21 00:53
It would be great if you could kindly close this issue, since it's not a bug. You can still follow HEAD and have this command under your disposal if you want. I linked you the docs for how to do that.

In my opinion, since you're just using a feature that is present in HEAD and not in stable version, it doesn't justify it being labeled as a bug.

**Comment by Freaksed** [comment] 2024-02-21 16:52
Thanks, closing now. Will this feature be making its way to stable?

**Closed** 2024-02-21 16:51 UTC
Labels: bug

**Comment by dpetka2001** [comment] 2024-02-21 17:26
There was a new stable release this morning, so it got merged. You can check it out by updating LazyVim.
