### ISSUE TITLE
bug: text is pasted when opening a file

### ISSUE THREAD

**Issue by Bouni** [LazyVim/LazyVim#3343] opened 2024-05-28 05:54 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Linux

### Describe the bug

When I open a file, taxt that I deleted earlier (with closing nvim in the meantime) is pasted into the document.

![Nvim](https://github.com/LazyVim/LazyVim/assets/948965/96804228-2a8d-486e-b9c5-60aa69b59ced)

### Steps To Reproduce

1. edit a file, delete some text
2. close nvim
3. open a file, the text is pasted

### Expected Behavior

Don't paste text at startup.

- I already tried various versions of neovim (0.9, 0.10.0, nightly).
- I deleted my config and cloned the lasyvim repo without any changes, the issue happens even with that
- The bug seems not to happen when I use the config below (repo.lua)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2024-05-28 06:02
Can't reproduce

**Comment by dpetka2001** [comment] 2024-05-28 08:02
Try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
5. Delete some text and restart Neovim with command from step 3
```
Do you observe the same behavior?

For cleanup
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by Bouni** [comment] 2024-05-28 12:10
@dpetka2001 I get the exact same behaviour!

Any ideas what plugin might cause this? I'm willing to disable whatever comes tou your mind in order to fix this.

I work from a Windows machine through an SSH tunnel on a Arch linux machine, ist that maybe part of the problem?

**Comment by dpetka2001** [comment] 2024-05-28 12:20
Maybe what you're using to ssh is messing with the `clipboard` and sends the clipboard? Not sure. Check the settings of the app you use for ssh. But if you're not able to reproduce locally on your pc, then I don't think this is a LazyVim bug.

**Comment by Bouni** [comment] 2024-05-28 12:43
I think I got something. 

- Windows Terminal + Powershell 7 -> Problem 
- Windows Terminal + Powershell 5 -> No Problem 
- Putty -> No Problem

Maybe some weird Powershell stuff going on 🤔

**Comment by folke** [comment] 2024-05-28 12:48
Seems similar to https://github.com/neovim/neovim/issues/29047

Either way, I'm closing this, since this is for sure not a LazyVim issue...

**Closed by folke** 2024-05-28 12:48 UTC
Labels: bug
