### ISSUE TITLE
bug: Command Mason not found after loading mason.nvim

### ISSUE THREAD

**Issue by mehalter** [LazyVim/LazyVim#1237] opened 2023-07-27 11:21 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 release

### Operating system/version

Arch Linux

### Describe the bug

On a completely clean installation of LazyVim everything seems to be working except the `:Mason` command. It seems to do something with how lazy is setting up the commands. For example, I can run `:lua require("mason.ui").open()`, but the first time I run `:Mason` I get

> Command `Mason` not found after loading `mason.nvim`

After thist first run of `:Mason` then every subsequent run afterwards gives the following error:

> E464: Ambiguous use of user-defined command

![2023-07-27_07:12:35_screenshot](https://github.com/LazyVim/LazyVim/assets/1591837/7baa99f3-2771-4c85-9ef3-486fb6bf8145)

### Steps To Reproduce

1. Using the `repro.lua` file below, run `nvim -u repro.lua`
2. After the installation completes, run `:Mason`
3. See the error

### Expected Behavior

I would expect user commands to be set up correctly such as `:Mason` rather than being required to use the lua API.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  { import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2023-07-27 17:17
Cannot reproduce with Lazyvim starter template. I can execute the command just fine.

**Comment by mehalter** [comment] 2023-07-27 17:19
@dpetka2001 my recording is actually using the Lazyvim starter template. This is also with a completely fresh environment clearing out the cache/data/state folders and being completely clean

**Comment by dpetka2001** [comment] 2023-07-27 17:21
Yes, me too. Just tried a completely new installation and was not able to reproduce.

**Comment by dpetka2001** [comment] 2023-07-27 17:22
Maybe something gone wrong with initial `Mason` installation and you encountered the error? What if you delete `~/.local/share/nvim/lazy/mason.nvim` and let `Lazy` reinstall it?

**Comment by mehalter** [comment] 2023-07-27 17:32
Actually @dpetka2001 I can reproduce from an already built LazyVim setup and just deleting `~/.local/share/nvim/lazy/mason.nvim`. On startup it installs the plugin and afterwards I cannot run `:Mason` until I restart the editor. I can run `:lua require("mason.ui").open()` so it's loading the plugin, something is just going on with the setup of the lazy loading on command.

**Comment by dpetka2001** [comment] 2023-07-27 17:33
Yes, because after it got installed, I believe it's not immediately loaded until you restart Neovim. Whereas, when you require it you also load it and can use it.

**Comment by mehalter** [comment] 2023-07-27 17:34
1. It should be lazy loaded on the command based on the lazyvim plugin spec
2. After calling `require("mason.ui").open()` I still cannot run `:Mason`

**Comment by mehalter** [comment] 2023-07-27 17:45
Nope! This is the exact process I was following before to make sure things were clean (granted, different folder names) I verified with your exact lines and things and still got the same result.

**Comment by dpetka2001** [comment] 2023-07-27 17:48
You have to restart the editor for the plugin to load. Otherwise you could try `Lazy reload mason.nvim`, so that `Mason` gets reloaded and you can execute the command afterwards.

**Comment by mehalter** [comment] 2023-07-27 17:50
Yeah, it's just an interesting bug because Telescope and other plugins seem to work just fine on fresh installation and lazy loading by command. It seems like with lazy.nvim this *should* work on installation since it sorta has this non-deterministic result of which plugins are working/not working on installation.

**Comment by dpetka2001** [comment] 2023-07-27 17:51
I think that `mason` gets loaded right after `build` and the commands are not available yet for the user, until the plugin reloads.

**Comment by mehalter** [comment] 2023-07-27 17:53
I appreciate you helping out and taking some time to look at this with me :) Hopefully this could potentially get resolve in lazy.nvim upstream to enable this to work :D

**Comment by dpetka2001** [comment] 2023-07-27 17:54
I don't know what to tell you on this. The maintainer must have a better response as to what is actually happening and how it should be handled.

**Comment by mehalter** [comment] 2023-07-27 17:54
Yeah no worries, folke I believe is on vacation for a bit so hopefully will get weighed in on at some point. Thanks for your time!

**Comment by dpetka2001** [comment] 2023-07-27 17:55
I'm just used to restarting the editor to load the plugins, because `Lazy reload` is a recent addition to `lazy.nvim` and when I started using Lazyvim, this wasn't even an option so you had to restart the editor.

**Comment by mehalter** [comment] 2023-07-27 17:58
Yeah I agree completely :) the main fix here should just not require Mason to need to be reloaded. It should be resolved on the installation and with the lazy loading that is specified. Once the plugin is installed it shouldn't be loaded until the lazy loading events (unless lazy loading is disabled) and then it should load correctly. The notification given regarding the loading on Command is actually coming from lazy.nvim. It is saying that the `:Mason` command did appropriately get lazy loaded but after loading the plugin the command was not available. This is a bug of it not correctly identifying that the command was set up when the plugin was loaded and putting the original command back in place.

**Comment by karanhiremath** [comment] 2023-09-26 06:44
I was having a similar issue and determined that probably the best way to resolve this issue would be to add 
```lsp
require("mason").setup()
```
in an `after/plug/lsp.lua` file that can be loaded once lazy/packer/etc. finishes the plugin loading

**Comment by folke** [comment] 2023-09-27 10:41
Fixed in https://github.com/folke/lazy.nvim/commit/24f6b6f1c7fb68f02335dd9579faee8b243e6a54
This was caused because during builds the plugin must be loaded before startup, but handlers were not correctly setup.

**Closed by folke** 2023-09-27 10:41 UTC
Labels: bug

**Comment by wonbinbk** [comment] 2024-06-09 22:58
> I was having a similar issue and determined that probably the best way to resolve this issue would be to add
> 
> ```commonlisp
> require("mason").setup()
> ```
> 
> in an `after/plugin/lsp.lua` file that can be loaded once lazy/packer/etc. finishes the plugin loading

Thank you.
Tried everything recommended in this thread, and updated Lazy too. But this is what actually fixed it for me.

**Comment by Sorcecoder** [comment] 2024-09-10 19:33
`sudo rm -r ~/.local/share/nvim/lazy` 
did the trick for me
