### ISSUE TITLE
gitsigns not showing anymore after i open NeoTree

### ISSUE THREAD

**Issue by GreenSleeper** [LazyVim/LazyVim#792] opened 2023-05-22 07:41 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Ubuntu x86_64  18.04.5 LTS

### Describe the bug

When i open a file, `gitsigns` are showing correctlly, but after I open `Neotree` and close it, `gitsigns` stop showing up.

### Steps To Reproduce

1. install lazyvim like in [installation](https://www.lazyvim.org/installation}
2. open a file that is tracked by git and has some changes
3. open neotree and close it

### Expected Behavior

`gitsigns` should show up after closing neotree

**Comment by folke** [comment] 2023-05-22 07:49
Can't reproduce. Did you set a custom `statuscolumn`?

**Comment by GreenSleeper** [comment] 2023-05-22 08:16
> Can't reproduce. Did you set a custom `statuscolumn`?

No, just freshly installed LazyVim

**Comment by GreenSleeper** [comment] 2023-05-22 08:32
BTW, I'm sshing to my ubuntu server in windows terminal, but i don't think this issue has anything to do with it.

**Comment by folke** [comment] 2023-05-22 08:40
Just did the same. Still can't reproduce. Are you sure it's not your terminal that somehow removes 1 column of cells for some reason?
The lines from gitsigns are very thin and on the left side.

What if you split the view in right/left and then open/close neo-tree?
Do the signs still appear on the right pane?

**Comment by folke** [comment] 2023-05-22 09:19
That's the default `diff` component from lualine, so the issue should be reported there. Closing this

**Closed by folke** 2023-05-22 09:19 UTC
Labels: bug
