### ISSUE TITLE
bug: Can't disable the bufferline's mapping of <S-h>, <S-l> to unveil original Vim motion

### ISSUE THREAD

**Issue by olatheander** [LazyVim/LazyVim#2066] opened 2023-11-25 23:11 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Arch Linux Kernel 6.6.2

### Describe the bug

I'm trying to disable bufferline's mapping of `<S-h>` and `<S-l>` to cycle buffers, i.e:
```
  {
    "akinsho/bufferline.nvim",
    event = "VeryLazy",
    keys = {
      ...
      ..
      { "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev buffer" },
      { "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next buffer" },
      ...
      ..
    },
```
by disabling the mappings as described in [Adding & Disabling Plugin Keymaps](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps):
```
return {
  {
      -- Other UI plugins
  },
...
..
  {
    "akinsho/bufferline.nvim",
    keys = {
      { "<S-h>", false },
      { "<S-l>", false },
    },
  },
}
```
in a [ui.lua](https://github.com/olatheander/nvim/blob/lazyvim/lua/plugins/ui.lua#L27-L28) file.

What I hoped for is that would unveil the default Vim motions for these mappings, i.e. "move to top of screen"/"move to bottom of screen".

I looked through a bunch of issues and my case resemble #1485 a bit but it doesn't matter if you provide arguments or not.

### Steps To Reproduce

1. default behavior of LazyVim is to cycle buffers for `<S-h>` and `<S-l>`
2. Add a file `lua/plugins/ui.lua` with the following content:
   ```
   {
    "akinsho/bufferline.nvim",
    keys = {
      { "<S-h>", false },
      { "<S-l>", false },
    },
   },
   ```
3. Reload nvim.
4. The keys still cycle buffers.

### Expected Behavior

The normal Vim motions for the key should be unveiled, i.e. "move to top of screen"/"move to bottom of screen" respectively.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2023-11-25 23:31
If you search for `<s-h>` in the search box for this repo, you will see these [results](https://github.com/search?q=repo%3ALazyVim%2FLazyVim%20%3Cs-h%3E&type=code) and you can see that `<s-h>` is defined in 2 places. One place is the `bufferline` spec like you already mentioned and the other place is in `lazyvim/config/keymaps.lua` as general keymaps that map to the vim `bnext/bprevious` for cycling buffers without Bufferline. So, in your `/lua/config/keymaps.lua` you have to delete those mappings as well. Not a bug either case.

**Comment by olatheander** [comment] 2023-11-26 00:26
Oh, totally missed the mapping in `keymaps.lua`. Deleting the mappings with `vim.keymap.del` did the trick. Thanks @dpetka2001 .

**Comment by dpetka2001** [comment] 2023-11-26 11:44
@olatheander Could you kindly close this issue if it's resolved?

**Closed** 2023-11-26 12:47 UTC
Labels: bug

**Comment by meleu** [comment] 2023-12-22 21:13
For those who reached here for the same reason as me, just add this to your `~/.config/nvim/lua/config/keymaps.lua`:
 
```lua
vim.keymap.del("n", "<S-h>")
vim.keymap.del("n", "<S-l>")
```

**Comment by davetrust** [comment] 2024-01-05 23:59
> For those who reached here for the same reason as me, just add this to your `~/.config/nvim/lua/config/keymaps.lua`:
> 
> ```lua
> vim.keymap.del("n", "<S-h>")
> vim.keymap.del("n", "<S-l>")
> ```

Appreciated when someone is helpful and clear and not patronizing to users who are puzzled as to why a tool behaves in an unexpected manner (ie overridding native Vim keybindings that are indeed used frequently)

**Comment by abeldekat** [comment] 2024-01-06 09:41
@davetrust,

You are indirectly saying: The [comment](https://github.com/LazyVim/LazyVim/issues/2066#issuecomment-1826442315) from @dpetka2001 is patronizing. You even added a thumb down.

I really dislike indirect qualifications and I think your comment is totally inappropriate.
Please, have a look at the closed issues in this repository. While you're at it, also have a look at the responses in the discussions.

I think the answer is very clear and helpful. It's important to understand the "why". And indeed, it's not a bug. That can happen.
