### ISSUE TITLE
bug: mini.starter: `buf_id` in `refresh()` is not an identifier of valid Starter buffer.

### ISSUE THREAD

**Issue by nexxai** [LazyVim/LazyVim#3207] opened 2024-05-17 19:35 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

macOS Sonoma 14.4.1 (23E224)

### Describe the bug

I use LazyVim and I haven't made any changes to it recently (beyond just the usual updating packages to their latest versions) but this error just started popping up as soon as I open NeoVim. I can make it go away by hitting q but I was wondering if there's a way to figure out why it started coming up out of nowhere.

I originally opened [this](https://github.com/echasnovski/mini.nvim/issues/884) ticket on the the `mini.nvim` plugin repo but it was closed by the author due to him believing it is an issue with LazyVim.

<img width="883" alt="331349225-23ad964f-a8df-4edd-b3ba-4412a5c324c0" src="https://github.com/LazyVim/LazyVim/assets/4316564/f7237cdd-82cf-4126-860b-6c0af0c022b3">

### Steps To Reproduce

1. Open NeoVim

### Expected Behavior

1. The error not to occur

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-05-17 19:53
Could you test the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
5. While on dashboard, press `x` to open the `LazyExtras` and toggle `ui.mini-starter` on by pressing `x` again
6. Restart Neovim with command provided in step 3 and observe behavior
```

For cleanup after you finished testing
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```
I can't reproduce it with default LazyVim settings.

**Comment by dpetka2001** [comment] 2024-05-17 19:56
I was able to reproduce by passing a directory as file argument.

**Comment by nexxai** [comment] 2024-05-17 22:07
> Could you test the following
> 
> ```shell
> 1. `mkdir ~/.config/lazytest`
> 2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
> 3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
> 4. Restart Neovim with the command provided in step 3
> 5. While on dashboard, press `x` to open the `LazyExtras` and toggle `ui.mini-starter` on by pressing `x` again
> 6. Restart Neovim with command provided in step 3 and observe behavior
> ```
> 
> For cleanup after you finished testing
> 
> ```shell
> rm -rf ~/.config/lazytest
> rm -rf ~/.local/share/lazytest
> rm -rf ~/.local/state/lazytest
> rm -rf ~/.cache/lazytest
> ```
> 
> I can't reproduce it with default LazyVim settings.

So I did all this and can confirm it happens when opening a directory using something like `NVIM_APPNAME=lazytest nvim .` or opening a file with something like `NVIM_APPNAME=lazytest nvim pint.json`

**Comment by dpetka2001** [comment] 2024-05-17 22:14
@nexxai Could you try #3209 to see if it solves your issue?

**Comment by nexxai** [comment] 2024-05-17 23:26
What's the best way to do that? Same steps above but reference that specific commit?

**Comment by dpetka2001** [comment] 2024-05-17 23:33
Create a file `~/.config/nvim/lua/plugins/core.lua` with following contents
```lua
return {
  {
    "dpetka2001/LazyVim", 
    branch = "fix/mini-starter", 
  }, 
}
```
Save the file and then open Lazy UI and press `U` to update.

**Comment by nexxai** [comment] 2024-05-17 23:37
Ok I feel like an idiot because I can see that branch on Github, but when I try to run the update, it fails.  Do I need to enable any special flags to tell it that it's ok to load from the not-usual repo?

<img width="636" alt="Screenshot 2024-05-17 at 5 36 02 PM" src="https://github.com/LazyVim/LazyVim/assets/4316564/668a7d15-6837-47c5-b835-2d644186e867">

**Comment by dpetka2001** [comment] 2024-05-17 23:53
I just press `C` to check and then `U` to update.

**Comment by nexxai** [comment] 2024-05-18 00:00
Tried again with a fresh install using the steps above and it looks good.  No more error on the folders and files I was having issues with before!

**Comment by dpetka2001** [comment] 2024-05-18 00:09
Cool. Plz delete that now, because i'm not sure if it gets merged. Maybe the maintainer will prefer another solution. I will keep this branch live until my PR gets merged or rejected.

**Comment by dpetka2001** [comment] 2024-05-18 07:55
@nexxai I just pushed a new change. Would appreciate if you could test it whenever you have time.

**Closed** 2024-05-18 08:07 UTC
Labels: bug

**Comment by echasnovski** [comment] 2024-05-18 13:22
The more robust solution looks to be testing if the current buffer comes from 'mini.starter' (`vim.bo.filetype == 'starter'`). Because if Neovim is opened with an explicit target, starter buffer is not shown, hence `refresh()` shows a message.

**Comment by dpetka2001** [comment] 2024-05-18 13:31
I replaced the call to `refresh` with `do VimResized`, since from what i read in the comments of `Ministarter.refresh` it also gets updated then. Does this potentially incur some unwanted effects?

**Comment by echasnovski** [comment] 2024-05-18 13:37
> I replaced the call to `refresh` with `do VimResized`, since from what i read in the comments of `Ministarter.refresh` it also gets updated then. Does this potentially incur some unwanted effects?

- It triggers all autocommands for `VimResized` event, from all plugins.
- It does not express proper intent (refresh starter buffer) which is not robust because 'mini.starter' can change `VimResized` behavior without any compatibility (docs mentioning is more about being aware about current implementation, not that it will always stay this way; although it probably will).

**Comment by dpetka2001** [comment] 2024-05-18 13:47
Will take another go at it later tonight. Thanks for the explanation and suggestions. Really appreciate you taking the time to chime in.
