### ISSUE TITLE
bug: edgy bufferline offsets

### ISSUE THREAD

**Issue by andresatierf** [LazyVim/LazyVim#3876] opened 2024-07-01 11:14 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11 10.0.22631.0

### Describe the bug

Starting nvim with edgy extra enabled throws the following error
![Screenshot 2024-07-01 121047](https://github.com/LazyVim/LazyVim/assets/29847057/7776068a-5791-4af4-a4a0-ab1d14d50834)

### Steps To Reproduce

1. open nvim with edgy extra enabled

### Expected Behavior

no errors on nvim start

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dotfrag** [comment] 2024-07-02 10:53
I cannot reproduce this problem with the steps provided, but I'm on Linux.

**Comment by dpetka2001** [comment] 2024-07-02 11:22
He must have some kind of personal config like
```lua
  {
    "folke/edgy.nvim",
    opts = {
      left = {},
      right = {},
    },
  },
```
and he gets that error. In that case [these 2 lines](https://github.com/LazyVim/LazyVim/blob/78cf6ee024cbf6a17dc8406555eb131994cd8b63/lua/lazyvim/plugins/extras/ui/edgy.lua#L160-L161) should be swapped I think. But I don't get why use `edgy` if you don't want any `left/right` components. But I guess it's just some personal preference.

**Comment by andresatierf** [comment] 2024-07-02 11:30
@dpetka2001 you're kinda right, but I didn't disable them. I just swapped them.
  {
    "folke/edgy.nvim",
    opts = function(_, opts)      
      opts.right = opts.left
      opts.left = nil
    end,
  },

**Comment by folke** [comment] 2024-07-02 11:36
you're removing some settings from an extra where others might depend on.
I could fix this for this use-case, but there's thousands of ways a user might alter an opts table in the wrong way,
so won't fix. Your own changes broke it. Why did you even post an issue about this in the first place?

**Closed by folke** 2024-07-02 11:36 UTC
Labels: bug

**Comment by dpetka2001** [comment] 2024-07-02 11:48
Something like this should work I believe
```lua
      local tmp = opts.right
      opts.right = opts.left
      opts.left = tmp
```
You shouldn't get the error any more. Not sure if there's another more correct way I fail to think of. I don't use edgy, so not sure if this might break some other settings.

**Comment by andresatierf** [comment] 2024-07-02 11:50
@dpetka2001 thanks for your help
