### ISSUE TITLE
feature: Toggle conform formatting

### ISSUE THREAD

**Issue by varac** [LazyVim/LazyVim#3024] opened 2024-04-20 08:33 UTC
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I'd like to maunally disable conform formatting for certain files and the ` <leader>uf` or `<leader>uF` key bindings only disable *LSP* formatting, not conform formatting. 

### Describe the solution you'd like

As I haven't used manually disabling formatting before I'd be fine if the already existing key bindings mentioned above would also disable conform formatting, but this might introduce a change for ppl used to these key bindings, so a dedicated key binding to only disable conform formatting might be better.

### Describe alternatives you've considered

Right now, I have to remove the specific conform formatter from the conform config each time I need it, which is not very practical.

### Additional context

I tried following the [conform documentation for disabling formatting on save](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save), but failed to make it work, as I'm not very good with LazyVim custom config options.

**Comment by dpetka2001** [comment] 2024-04-20 09:00
Those keys do actually disable conform formatting as well. I tried with default LazyVim settings in Lua files, which by default uses stylua in conform to format, and when I disabled formatting with `<leader>uf` it didn't format at all.

**Comment by varac** [comment] 2024-04-20 09:53
That's weird. Here's my noice history when toggling format with `<leader>uf`, both times is see `conform.nvim ***(active)***` regardless that LSP is toggling fine: 

```
   Warn  11:46:50 notify.warn LazyFormat (disabled) # Status
- [ ] global **disabled**
- [ ] buffer **inherit**

# conform.nvim ***(active)***
- [x] **stylua**

# LSP
- [ ] **lua_ls**
   Info  11:46:56 notify.info LazyFormat (enabled) # Status
- [x] global **enabled**
- [x] buffer **inherit**

# conform.nvim ***(active)***
- [x] **stylua**
```

Maybe it's the way I am configuring  conform ? 

```
return {
  {
    -- https://github.com/stevearc/conform.nvim?tab=readme-ov-file#setup
    -- https://www.lazyvim.org/plugins/formatting#conformnvim
    "stevearc/conform.nvim",
    opts = function()
      local plugin = require("lazy.core.config").plugins["conform.nvim"]
      local opts = {
        -- /home/varac/.local/state/nvim/conform.log
        log_level = vim.log.levels.DEBUG,
        format = {
          timeout_ms = 3000,
          async = false,
          quiet = false,
        },
        ---@type table<string, conform.FormatterUnit[]>
        formatters_by_ft = {
          beancount = { "bean-format" },
          lua = { "stylua" },
          markdown = { "mdformat" },
          -- https://docs.astral.sh/ruff/faq/#is-the-ruff-linter-compatible-with-black
          -- Black is only added to fix long lines, with `--preview` enabled in
          -- `~/pyproject.toml`, because I can't make it work with `ruff format`
          python = { "black", "ruff_format" },
          -- beautysh: last commit 2023-04, defaults to 4 spaces for indentation
          sh = { "shfmt", "shellharden" },
          -- https://www.lazyvim.org/extras/lang/terraform#conformnvim-optional
          terraform = { "terraform_fmt" },
          tf = { "terraform_fmt" },
          ["terraform-vars"] = { "terraform_fmt" },
          -- yamlfix and yamlfmt are both in maintenance mode / slow
          yaml = { "prettier" },
        },
        -- The options you set here will be merged with the builtin formatters.
        -- You can also define any custom formatters here.
        ---@type table<string, conform.FormatterConfigOverride|fun(bufnr: integer): nil|conform.FormatterConfigOverride>
        formatters = {
          injected = { options = { ignore_errors = true } },
        },
      }
      return opts
    end,
  },
}
```

**Comment by dpetka2001** [comment] 2024-04-20 10:23
LazyVim implements its own formatter, which makes use of both conform and lsp. What is important is what you're seeing in status. That is the status of the LazyVim formatter. The easiest thing is to try it out. When I toggle formatting off with `<leader>uf`, no formatting takes place whatever changes I make to the file. Simple as that.

**Comment by folke** [comment] 2024-04-22 08:22
closing, since toggling formatting works

**Closed by folke** 2024-04-22 08:22 UTC
Labels: enhancement

**Comment by moliyu** [comment] 2024-04-28 02:53
> closing, since toggling formatting works

How could I disable formatting default.

**Comment by ilveroluca** [comment] 2024-06-06 13:21
I'm also seeing conform.nvim formatting always shown as "active", even if automatic formatting is indeed disabled.  The screenshot below captures the status displayed after quickly  toggling autoformatting off/on twice in succession: 
![image](https://github.com/LazyVim/LazyVim/assets/1502936/a931d3bc-a879-4bfa-873d-c3886974759a)

Is this expected behaviour?

**Comment by dpetka2001** [comment] 2024-06-06 13:50
Yes, it's expected behavior. You should be looking at the `Status` and the title of the window. Those indicate if formatting is enabled or disabled globally or for the buffer. `conform` will always show as active source except if there's no formatter for a filetype defined and then fall back to the LSP formatting if the LSP server supports it.

**Comment by ilveroluca** [comment] 2024-06-07 06:45
Thanks for the clarification!
