### ISSUE TITLE
Almost stock config : Regularly consuming 3 to 7 gb of RAM

### ISSUE THREAD

**Issue by StitiFatah** [LazyVim/LazyVim#806] opened 2023-05-24 07:29 UTC
Hi, 

I'm on Arch, last version of neovim, system up to date. 

I've an almost stock config of LazyVim, I've updated everything and actually on a Typescript project /usr/bin/nvim frequently takes that much RAM after few minutes/hours although it's close to 50mb at boot. 

Copilot ts server tailwind LSP etc take in the range 100-200mb each but it's the nvim process itself that shows these numbers. 

Would you know what plugin could be responsible for that ? 

Thanks in advance.

**Comment by folke** [comment] 2023-05-24 08:53
You also didn't set `version="*"` for cmp for example?

**Comment by StitiFatah** [comment] 2023-05-24 08:58
Yes I've updated after your PR and also like 2 days ago, I'm at the last commit

**Comment by folke** [comment] 2023-05-24 09:29
I don't have any memory issues anymore.

Really no idea and this will obviously also not be caused by LazyVim, but by one of the plugins.

I'll close this, but do let me know if you'd find what plugin is causing this.

**Comment by StitiFatah** [comment] 2023-05-24 09:29
> You also didn't set `version="*"` for cmp for example? Or you aren't using a local `dev` version?

I haven't touched anything, here is a screenshot from the ":Lazy" UI 
![nvim_cmp](https://github.com/LazyVim/LazyVim/assets/68331131/3c2d232b-e139-4999-a5d9-1287344f91bf)

**Comment by utkarshgupta137** [comment] 2023-05-24 09:32
@StitiFatah May I ask how you're measuring memory usage? Most memory usage indicators can be wildly inaccurate, especially on macOS. Have you compared the memory usage of LazyVim and clean Nvim (`nvim --clean`)? Maybe it is related to TS LSP or something.

**Comment by StitiFatah** [comment] 2023-05-24 09:32
> I don't have any memory issues anymore.
> 
> Really no idea and this will obviously also not be caused by LazyVim, but by one of the plugins.
> 
> I'll close this, but do let me know if you'd find what plugin is causing this.

Yes i'll try to experiment and let you know, just now I'm at 282mb, I was at like 50 when I opened this issue, I notice it because I'm often at like 10+gb of RAM used with just a few chromium tabs and nvim opened

**Comment by utkarshgupta137** [comment] 2023-05-24 09:36
> just a few chromium

There's your answer :)
For me, nvim usually takes around 250MB, which I can't say is much these days. This is with rust-analyzer.

Have you looked at the memory usage of the browser?

**Comment by StitiFatah** [comment] 2023-05-24 09:37
> Just to be sure, you are talking about resident ram right? Not virtual?

yes

**Comment by folke** [comment] 2023-05-24 09:37
Would be great if you could somehow reproduce this, so we can filter down the possible plugins that may be causing this.

2GB is indeed not normal.

**Comment by StitiFatah** [comment] 2023-05-24 09:37
> > just a few chromium
> 
> There's your answer :) For me, nvim usually takes around 250MB, which I can't say is much these days. This is with rust-analyzer.
> 
> Have you looked at the memory usage of the browser?

My answer ? How would chromium be shown under /usr/bin/nvim ?

**Comment by folke** [comment] 2023-05-24 09:38
How quicky does it get to over 1GB? And what are the things you did?

**Comment by utkarshgupta137** [comment] 2023-05-24 09:39
> > > just a few chromium
> > 
> > 
> > There's your answer :) For me, nvim usually takes around 250MB, which I can't say is much these days. This is with rust-analyzer.
> > Have you looked at the memory usage of the browser?
> 
> My answer ? How would chromium be shown under /usr/bin/nvim ?

I meant in case btop wasn't reporting something correctly, it would show large usage for the browser too.

**Comment by StitiFatah** [comment] 2023-05-24 09:41
> How quicky does it get to over 1GB? And what are the things you did?

I'd say usually after few hours, right now I'm at 282 mb for /usr/bin/nvim, when I opened the issue I was at around 50mb, but I feel it's not consistent. 

> > > > just a few chromium
> > > 
> > > 
> > > There's your answer :) For me, nvim usually takes around 250MB, which I can't say is much these days. This is with rust-analyzer.
> > > Have you looked at the memory usage of the browser?
> > 
> > 
> > My answer ? How would chromium be shown under /usr/bin/nvim ?
> 
> I meant in case btop wasn't reporting something correctly, it would show large usage for the browser too.

No it has nothing to do my browser, closing nvim indeed frees up this RAM

**Comment by StitiFatah** [comment] 2023-05-24 09:42
> > How quicky does it get to over 1GB? And what are the things you did?
> 
> I'd say usually after few hours, right now I'm at 282 mb for /usr/bin/nvim, when I opened the issue I was at around 50mb, but I feel it's not consistent. i'm actually working on a solidjs Typescript project with tailwind, that's mostly what I am doing actually
> 
> > > > > just a few chromium
> > > > 
> > > > 
> > > > There's your answer :) For me, nvim usually takes around 250MB, which I can't say is much these days. This is with rust-analyzer.
> > > > Have you looked at the memory usage of the browser?
> > > 
> > > 
> > > My answer ? How would chromium be shown under /usr/bin/nvim ?
> > 
> > 
> > I meant in case btop wasn't reporting something correctly, it would show large usage for the browser too.
> 
> No it has nothing to do my browser, closing nvim indeed frees up this RAM

**Comment by folke** [comment] 2023-05-24 09:43
Do you still have an nvim session open that uses lots of memory?

Can you run the code below in a new buffer inside that session?

```lua
local nsn = vim.api.nvim_get_namespaces()

local counts = {}

for name, ns in pairs(nsn) do
  local count = 0
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    count = count + #vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {})
  end
  counts[#counts + 1] = { name = name, count = count }
end
table.sort(counts, function(a, b)
  return a.count > b.count
end)
vim.print(counts)
```

**Comment by StitiFatah** [comment] 2023-05-24 09:45
> Do you still have an nvim session open that uses lots of memory?
> 
> Can you run the code below in a new buffer inside that session?
> 
> ```lua
> local nsn = vim.api.nvim_get_namespaces()
> 
> local counts = {}
> 
> for name, ns in pairs(nsn) do
>   local count = 0
>   for _, buf in ipairs(vim.api.nvim_list_bufs()) do
>     count = count + #vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {})
>   end
>   counts[#counts + 1] = { name = name, count = count }
> end
> table.sort(counts, function(a, b)
>   return a.count > b.count
> end)
> vim.print(counts)
> ```

No I don't, the current one is at 282mb,  but I'll make sure to not close it this afternoon and run this code after a while

**Comment by folke** [comment] 2023-05-24 09:46
I updated that code snippet. Can you run it in your current session? 282mb also seems too much

**Comment by StitiFatah** [comment] 2023-05-24 09:50
> I updated that code snippet. Can you run it in your current session? 282mb also seems too much

Could you please give me instructions on how to do that ? Should I do :source path/to/script.lua ?

**Comment by folke** [comment] 2023-05-24 09:51
`:edit test.lua`
paste the code

`:luafile %`

**Comment by folke** [comment] 2023-05-24 09:52
I found an issue with cmp/noice. Not sure that;s what causing it for you.
Basically extmarks are never cleared in the cmp doc window.

**Comment by folke** [comment] 2023-05-24 09:54
Updated code:
```lua
local nsn = vim.api.nvim_get_namespaces()

local counts = {}

for name, ns in pairs(nsn) do
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    local count = #vim.api.nvim_buf_get_extmarks(buf, ns, 0, -1, {})
    if count > 0 then
      counts[#counts + 1] = {
        name = name,
        buf = buf,
        count = count,
        ft = vim.bo[buf].ft,
      }
    end
  end
end
table.sort(counts, function(a, b)
  return a.count > b.count
end)
vim.print(counts)
```

**Comment by StitiFatah** [comment] 2023-05-24 09:54
> `:edit test.lua` paste the code
> 
> `:luafile %`

Where would I get the output of the script ?

**Comment by folke** [comment] 2023-05-24 09:56
:mess

**Comment by folke** [comment] 2023-05-24 10:32
Fixed in noice. Please update. And thanks for looking into this!

**Closed by folke** 2023-05-24 10:32 UTC

**Comment by StitiFatah** [comment] 2023-05-24 12:48
> Would be great if you could report back whether memory usage seems more stable now

Yes I was just experimenting before your update and while scrolling through tailwind classes it skyrocketed from 100 to 300 and quickly reached  417, thought it was still a tailwind problem. 

here is the output of the script jsut before your update : 

```lua
{ {
    buf = 147,
    count = 3798,
    ft = "cmp_docs",
    name = "messages_highlights"
  }, {
    buf = 22,
    count = 1156,
    ft = "typescriptreact",
    name = "indent_blankline"
  }, {
    buf = 434,
    count = 244,
    ft = "typescriptreact",
    name = "vim_lsp_semantic_tokens:5"
  }, {
    buf = 451,
    count = 180,
    ft = "typescriptreact",
    name = "vim_lsp_semantic_tokens:5"
  }, {
    buf = 22,
    count = 145,
    ft = "typescriptreact",
    name = "vim_lsp_semantic_tokens:5"
  }, {
    buf = 1152,
    count = 81,
    ft = "lua",
    name = "vim_lsp_semantic_tokens:7"
  }, {
    buf = 451,
    count = 56,
    ft = "typescriptreact",
    name = "indent_blankline"
  }, {
    buf = 434,
    count = 51,
    ft = "typescriptreact",
    name = "indent_blankline"
  }, {
    buf = 1153,
    count = 18,
    ft = "noice",
    name = "nui.nvim"
  }, {
    buf = 22,
    count = 14,
    ft = "typescriptreact",
    name = "Luasnip"
  }, {
    buf = 1152,
    count = 12,
    ft = "lua",
    name = "indent_blankline"
  }, {
    buf = 1154,
    count = 3,
    ft = "noice",
    name = "messages_highlights"
  } }


```

I've updated and now quickly reached 229mb, I'm going back to work now and will report back the evolution here. 

Thanks for all

**Comment by StitiFatah** [comment] 2023-05-24 14:05
One hour in, same project, same files, 264mb, voluntarily used the completion a couple of times, so I guess it seems to be fixed, I'll report again at the end of the day or before if I see memory usage spikes

**Comment by StitiFatah** [comment] 2023-05-24 17:41
So the session I was talking about in my last message finally peaked at 280ish mb after 3-4 hours, I closed it by accident and the new one is at 190mb after 1h45, so far so good.

**Comment by folke** [comment] 2023-05-24 20:04
ok, great. Super glad this is solved. Thanks again for bringing this under my attention!

**Comment by StitiFatah** [comment] 2023-05-24 20:07
> ok, great. Super glad this is solved. Thanks again for bringing this under my attention!

No problem, I should be the one thanking you for your help.
