### ISSUE TITLE
bug(noice): opts configuration in LazyVim not applying

### ISSUE THREAD

**Issue by emnnipal** [LazyVim/LazyVim#4936] opened 2024-12-02 16:58 UTC
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.1.1

### Describe the bug

The opts configuration for folke/noice.nvim in LazyVim isn’t working as expected. None of the options set in the opts table are taking effect.

- `lsp.hover.silent = true` is not working:
![Image](https://github.com/user-attachments/assets/e0377db3-b0b1-4496-bcc7-d269ea1c8d8b)

- No border in hover docs:
![Image](https://github.com/user-attachments/assets/f42cf48b-181f-47c8-abc8-07096e63269f)

### Steps To Reproduce

1. Configure the plugin in LazyVim using the following code snippet:
```
{
  "folke/noice.nvim",
  opts = {
    lsp = {
      hover = {
        silent = true, -- set to true to not show a message if hover is not available
      },
    },
    presets = {
      lsp_doc_border = true,
    },
    views = {
      hover = {
        border = {
          padding = { 0, 0 },
        },
      },
    },
  },
}
```

2. Save and reload Neovim.
3. Test hover functionality and other LSP-related features configured in opts.

### Expected Behavior

- The lsp.hover.silent setting should suppress hover error messages.
- The presets.lsp_doc_border setting should apply an LSP document border.
- The views.hover.border configuration should set the padding for the hover view.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment] 2024-12-02 17:12
Sorry, but I can't reproduce this:

![Image](https://github.com/user-attachments/assets/38e3f8a4-8bd9-4af0-a7d7-cfbbf705cfb4)

You're either overriding the lsp hover keymap or you're not correctly including that noice spec.

Either way, 100% certain user error. Closing.

**Comment by folke** [comment] 2024-12-02 17:13
btw, the fact that you have that TS icon in that hover, confirms, that this is **NOT** noice.

**Closed by folke** 2024-12-02 17:12 UTC
Labels: bug

**Comment by emnnipal** [comment] 2024-12-02 17:42
Thank you for pointing that out! It was really helpful. I managed to fix the issue and for context, here’s the solution:

![Image](https://github.com/user-attachments/assets/f969fc4c-84b7-4d36-852c-2bb9c093b238)

**Comment by OnlyWick** [comment] 2024-12-04 07:36
Werid, with the default lazyvim configuration, there is indeed no border hint in TypeScript file.
