### ISSUE TITLE
bug: Error in decoration provider vim_lsp_inlayhint.win: Error executing lua: ...acos-arm64/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:366: Invalid 'col': out of range

### ISSUE THREAD

**Issue by eiiot** [LazyVim/LazyVim#4500] opened 2024-09-27 01:34 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

MacOS 14.5

### Describe the bug

I run into this issue fairly frequently when editing bouts of code, often because there are errors in the code I'm editing. Running `:e` will often temporarily solve the issue but not fix it. I've tried removing all custom plugins and `.lua` config, but the issue remains. Other times, the issue will occur and updating the mason languages will fix it.

I am happy to do more troubleshooting and disable more things, if needed.

### Steps To Reproduce

1. Open a file, and induce some code that causes an error to be shown in the treesitter.
2. See above.

### Expected Behavior

neovim does not throw an error.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by eiiot** [comment] 2024-09-27 01:41
I'm unable to reproduce this with the `repro.lua` file, so this may be an issue on my end. Maybe close for now, and I'll see if I can get it to happen again?

**Comment by lynndylanhurley** [comment] 2024-09-29 17:37
i'm seeing this same issue with a fresh install of LazyVim. here is the full stacktrace:

```
Error in decoration provider vim_lsp_inlayhint.win:
Error executing lua: ...AD-f55213c/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:360: Invalid 'col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...AD-f55213c/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:360: in function <...AD-f55213c/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:314>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	.../share/nvim/lazy/nvim-notify/lua/notify/service/init.lua:63: in function 'push'
	...ocal/share/nvim/lazy/nvim-notify/lua/notify/instance.lua:77: in function <...ocal/share/nvim/lazy/nvim-notify/lua/notify/instance.lua:41>
	...e/nvim/lazy/noice.nvim/lua/noice/view/backend/notify.lua:168: in function '_notify'
	...e/nvim/lazy/noice.nvim/lua/noice/view/backend/notify.lua:198: in function 'show'
	...local/share/nvim/lazy/noice.nvim/lua/noice/view/init.lua:156: in function <...local/share/nvim/lazy/noice.nvim/lua/noice/view/init.lua:154>
	[C]: in function 'xpcall'
	...local/share/nvi
```

**Comment by OverVlad** [comment] 2024-09-30 17:45
> i'm seeing this same issue with a fresh install of LazyVim. here is the full stacktrace:
> 
> ```
> Error in decoration provider vim_lsp_inlayhint.win:
> Error executing lua: ...AD-f55213c/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:360: Invalid 'col': out of range
> stack traceback:
> 	[C]: in function 'nvim_buf_set_extmark'
> 	...AD-f55213c/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:360: in function <...AD-f55213c/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:314>
> 	[C]: in function 'nvim_exec2'
> 	vim/_editor.lua: in function 'cmd'
> 	.../share/nvim/lazy/nvim-notify/lua/notify/service/init.lua:63: in function 'push'
> 	...ocal/share/nvim/lazy/nvim-notify/lua/notify/instance.lua:77: in function <...ocal/share/nvim/lazy/nvim-notify/lua/notify/instance.lua:41>
> 	...e/nvim/lazy/noice.nvim/lua/noice/view/backend/notify.lua:168: in function '_notify'
> 	...e/nvim/lazy/noice.nvim/lua/noice/view/backend/notify.lua:198: in function 'show'
> 	...local/share/nvim/lazy/noice.nvim/lua/noice/view/init.lua:156: in function <...local/share/nvim/lazy/noice.nvim/lua/noice/view/init.lua:154>
> 	[C]: in function 'xpcall'
> 	...local/share/nvi
> ```

+1 for me. The same error

**Comment by lynndylanhurley** [comment] 2024-09-30 18:32
@eiiot seems like others are still having this issue. Can you re-open please?

**Comment by dpetka2001** [comment] 2024-09-30 19:00
This seems similar to #3284 that was closed as not LazyVim related, but Neovim trying to render outdated inlay hints. So, from what I read it either has to do with a Neovim upstream bug or some specific LSP not returning valid inlay hints positions.

Probably best to wait on maintainer's input on this as he is more knowledgeable about the issue at hand.

**Comment by eiiot** [comment] 2024-10-01 18:28
Will reopen given other people are running into this – day 3 of my fresh install and I'm also running into this error:

```
vtsls: -32603: Request textDocument/inlayHint failed with message: <semantic> TypeScript Server Error (5.3.3)
Debug Failure. Unexpected node.
Node IndexSignature was unexpected.
Error: Debug Failure. Unexpected node.
Node IndexSignature was unexpected.
```

Seems to be possibly related?

**Comment by dpetka2001** [comment] 2024-10-01 18:35
This is the same error as a user mentions [here](https://github.com/LazyVim/LazyVim/issues/3465#issuecomment-2254540943). In the next comment the author of `vtsls` mentions that that error is fixed in Typescript version 5.4. 

There's also an open issue at `vtsls` repo about the error that you mention as you can see [here](https://github.com/yioneko/vtsls/issues/159#issuecomment-2159349677). It seems to come directly from the LSP server and doesn't seem to have anything to do with LazyVim from what I've read so far.

**Comment by lynndylanhurley** [comment] 2024-10-01 21:16
@dpetka2001 our project is using typescript `v5.4.3`.

**Comment by dpetka2001** [comment] 2024-10-01 21:39
I'm not the one you should be asking about this. Rather the creator of `vtsls` LSP server. I already linked an open issue in my previous post about the error for inlay hints. It's not solved yet. 

Look at this [comment](https://github.com/yioneko/vtsls/issues/159#issuecomment-2120701175) by the creator himself. He suggests this is an issue with tsserver itself upstream and also links to the upstream issue https://github.com/microsoft/TypeScript/issues/53984. That issue was closed without referencing any solution. 

The last Typescript version it was tested mentioned by the bot that still reproduced the issue was Typescript 5.4.2. Still there's a user comment at the end of that issue that is asking for clarifications if it was fixed or not because the issue was closed without referencing a solution.

**Comment by lynndylanhurley** [comment] 2024-10-01 22:41
For context, up until about a week ago I had been using my own custom non-lazyvim config for years, and I never ran into this issue while using either `vtsls` or `typescript-language-server`. 

I must have not had inlay hints enabled. I'm going to try disabling.

**Comment by dpetka2001** [comment] 2024-10-01 22:57
Just enable `:lua vim.lsp.inlay_hints.enable(true)` with your old configuration and compare.

**Comment by loqusion** [comment] 2024-10-02 01:07
I'm able to reproduce the issue with a minimal config. Here are the steps I took:

1. Run Neovim with `nvim -u mini.lua` (contents below)
2. `:MasonInstall typescript-language-server`
3. Close and reopen the editor
4. Open `a.ts` (contents below)
5. Press `O` (`S-o`) on line 1

`mini.lua`

```lua
local function setup()
  if vim.env.LAZY_STDPATH then
    local root = vim.fn.fnamemodify(vim.env.LAZY_STDPATH, ":p")
    for _, name in ipairs({ "config", "data", "state", "cache" }) do
      vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
    end
  end

  if vim.env.LAZY_PATH and not vim.uv.fs_stat(vim.env.LAZY_PATH) then
    vim.env.LAZY_PATH = nil
  end

  local lazypath = vim.env.LAZY_PATH or vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
  if not vim.env.LAZY_PATH and not (vim.uv or vim.loop).fs_stat(lazypath) then
    vim.api.nvim_echo({
      {
        "Cloning lazy.nvim\n\n",
        "DiagnosticInfo",
      },
    }, true, {})
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local ok, out = pcall(vim.fn.system, {
      "git",
      "clone",
      "--filter=blob:none",
      lazyrepo,
      lazypath,
    })
    if not ok or vim.v.shell_error ~= 0 then
      vim.api.nvim_echo({
        { "Failed to clone lazy.nvim\n", "ErrorMsg" },
        { vim.trim(out or ""), "WarningMsg" },
        { "\nPress any key to exit...", "MoreMsg" },
      }, true, {})
      vim.fn.getchar()
      os.exit(1)
    end
  end
  vim.opt.rtp:prepend(lazypath)
end

local runtime_dir = vim.env.XDG_RUNTIME_DIR
vim.env.LAZY_STDPATH = vim.fs.joinpath(runtime_dir, "lazy_mini")
setup()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
    { import = "lazyvim.plugins.extras.lang.typescript" },
  },
})
```

`a.ts`

```typescript
function f() {
  return "Hello world"
}
```

## Solution

Because of the [rename from `tsserver` to `ts_ls`](https://github.com/neovim/nvim-lspconfig/pull/3232), [the code that disables `typescript-language-server`](https://github.com/LazyVim/LazyVim/blob/a1c3ec4cd43fe61e3b614237a46ac92771191c81/lua/lazyvim/plugins/extras/lang/typescript.lua#L22-L24) is outdated. So when `typescript-language-server` is installed by mason.nvim, it runs at the same time as `vtsls`.

`typescript-language-server` should be disabled in [`extras/lang/typescript.lua`](https://github.com/LazyVim/LazyVim/blob/a1c3ec4cd43fe61e3b614237a46ac92771191c81/lua/lazyvim/plugins/extras/lang/typescript.lua) like so:

```lua
{
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      ts_ls = { enabled = false },
    },
  },
},
```

When applying it to `mini.lua`, the error goes away:

```diff
--- mini.lua	2024-10-01 19:48:22.183802698 -0500
+++ fix.lua		2024-10-01 19:48:19.521775037 -0500
@@ -48,5 +48,13 @@
     { "LazyVim/LazyVim", import = "lazyvim.plugins" },
     -- add any other plugins here
     { import = "lazyvim.plugins.extras.lang.typescript" },
+    {
+      "neovim/nvim-lspconfig",
+      opts = {
+        servers = {
+          ts_ls = { enabled = false },
+        },
+      },
+    },
   },
 })
```

**Comment by dpetka2001** [comment] 2024-10-02 01:34
`typescript-language-server` is not installed by default. That's something that a user specifically installs. I thought we were talking about the default Typescript Extra. Minimal repros should be done with only the minimal repro available in the bug issue template and the corresponding Extras enabled. No user configuration should take place.

**Comment by loqusion** [comment] 2024-10-02 01:39
> That's something that a user specifically installs.

Not necessarily. It can be leftover from before the switch to `vtsls` took place.

In any case, I don't see what relevance that has. Just because `typescript-language-server` happens to be installed doesn't mean the user deserves to suffer through incessant mysterious error messages.

**Comment by loqusion** [comment] 2024-10-02 01:41
Anyway, I'm turning off notifications. Not interested in a pedantic back-and-forth.

**Comment by dpetka2001** [comment] 2024-10-02 01:59
> Just because typescript-language-server happens to be installed doesn't mean the user deserves to suffer through incessant mysterious error messages.

True. If that's really the problem, then the PR will fix it. But the issues i linked from vtsls repo with the same error msg as OP mentioned are 4 months old, way before the renaming of `typescript-language-server` happened. I hope it's what you say it is, but from what i've read it seems something deeper (of course i might be wrong).

**Comment by aasutossh** [comment] 2024-10-02 04:09
I had this previously, I updated the neovim (I use the master branch of neovim). After the upgrade I didn't have this.

**Comment by folke** [comment] 2024-10-02 07:32
Should be fixed by https://github.com/LazyVim/LazyVim/pull/4406

Either way, this is not a LAzyVim issue, but an issue between tsserver and Neovim's inlay hints

**Closed by folke** 2024-10-02 07:32 UTC
Labels: bug

**Comment by lynndylanhurley** [comment] 2024-10-03 18:26
This has been resolved for me 👍

**Comment by stucash** [comment] 2024-10-08 21:08
This isn't a language specific or LazyVim related one but given this one has been re-opened for the awareness, I'd like to mention that the exact same error happened to me in Rust. It certainly is something upstream I believe.

**Comment by lbrame** [comment] 2025-08-30 11:13
I'd like to pitch in real quick - I do not use LazyVim (I am on a slightly modified kickstart configuration) and I have been getting this a lot with `rustaceanvim`. Again, all is pretty much standard and with default values. I would exclude a problem with LazyVim in particular
