### ISSUE TITLE
bug: Rust LazyVim Extra package not working properly out of box

### ISSUE THREAD

**Issue by bubuntux** [LazyVim/LazyVim#2141] opened 2023-12-05 23:47 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Linux indell 6.6.3-200.fc39.x86_64

### Describe the bug

Rust language package from the extra configurations doesn't work properly out of box, it doesn't mark errors or autocomplete methods.

### Steps To Reproduce

Default install
1.  mv ~/.config/nvim{,.bak}
2. mv ~/.local/share/nvim{,.bak}
3. mv ~/.local/state/nvim{,.bak}
4. mv ~/.cache/nvim{,.bak}
5. git clone https://github.com/LazyVim/starter ~/.config/nvim
6. rm -rf ~/.config/nvim/.git
7. nvim

Install Rust lang package
1 .nvim
2. Press x (to enter Lazy Extras menu)
3. Search for lang.rust and enable it using x 

Create empty rust project
1.  cargo init abc
2. nvim abc
3. Open main.rs
4. add an extra invalid line inside of the main function  like `"hello".asdf();` 
5. Save 

No error is displayed, when you type "hello". you should get methods available such as trim or chars, instead you see only Snippets

### Expected Behavior

Error should be displayed on the invalid line  and autocomplete should suggest valid methods not only Snippets 

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",

require("lazy").setup({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "plugins" },
  },
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by kul-sudo** [comment] 2024-01-12 10:20
The issue seems to come in different forms, and I don't know why: #2345. Something's definitely broken, yes.

**Comment by dpetka2001** [comment] 2024-01-12 12:30
@bubuntux I cannot reproduce this. I get methods such as `trim` and `chars` when I type `"hello".`

How did you install Rust in your OS? There was another issue that had problems with Rust installed via the distro's package manager (see this [comment](https://github.com/LazyVim/LazyVim/issues/2201#issuecomment-1859140068)). 

Could you try installing Rust via `rustup` as per the official Rust [docs](https://www.rust-lang.org/tools/install) and see if you still have a problem?

**Comment by kul-sudo** [comment] 2024-01-20 11:57
Try to do `cargo clean`. This is what helped me fix a big issue with Rust.

**Comment by dpetka2001** [comment] 2024-01-21 17:10
Pretty sure it has something to do with the Rust installation itself. OP also created a Discussion in [AstroNvim](https://github.com/AstroNvim/astrocommunity/discussions/674) and it seems that he uses some kind of container and uses the distro's package manager to install Rust. Based on the comment I linked in my previous post, I believe it has something to do with that. That's why I asked if he could install Rust via `rustup` and check again.

**Comment by dpetka2001** [comment] 2024-01-23 13:03
@bubuntux I saw in the other thread in AstroNvim repo, that I linked above, that you use docker containers to run Neovim. I tried it and it seems it has something to do with the Rust version that the Alpine package manager distributes. If you install Rust with the method that is suggested from the official Rust docs, then it works fine (at least from the testing that i did). 

The following command is what I used
```bash
docker run -w /root -it --rm alpine:edge sh -uelic '
     apk add curl bash git lua nodejs npm lazygit bottom python3 go neovim ripgrep alpine-sdk --update
     curl --proto \'=https\' --tlsv1.2 -sSf https://sh.rustup.rs | sh
     source ~/.cargo/env
     git clone --depth 1 https://github.com/LazyVim/starter ~/.config/nvim
     sleep 5
     sed -i \'/{ "LazyVim\/LazyVim", import = "lazyvim.plugins" },/a { import = "lazyvim.plugins.extras.lang.rust" },\'  ~/.config/nvim/lua/config/lazy.lua
     cargo init abc
     nvim abc/src/main.rs
   '
```
With this I get the methods that you mentioned.

@folke This doesn't seem to be a LazyVim bug to me from the testing that I did, rather a problem with the Rust version that the Alpine package manager distributes. I don't know the internals being used from Neovim LSP about how it works with LSP servers installed via distro package managers and why they might be incompatibilities, but it is what it is.

**Comment by Verisana** [comment] 2024-01-24 15:23
Hello @dpetka2001 ,
I don't know if it is related, but I have almost similar problem with `rust-analyzer`. First, I thought it might be pure `rust-analyzer`, but it works there.
All problems started happening, when I updated to latest `rust-analyzer` version.
It doesn't show all error messages, but `clippy` warnings are showed.

When I disable/enable diagnostics, I spot three different behaviors:
1/ It enables normally => but Rust errors are not shown
2/ It stuck and need to kill a pane
3/ It shows this error:

```
E5108: Error executing lua: .../nvim/2819/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1031: Invalid 'line': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	.../nvim/2819/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1031: in function 'show'
	.../nvim/2819/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1223: in function 'show'
	.../nvim/2819/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1179: in function 'show'
	.../nvim/2819/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1173: in function 'show'
	.../nvim/2819/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1595: in function 'enable'
	...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/toggle.lua:48: in function 'diagnostics'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/config/keymaps.lua:119: in function <...l/share/nvim/lazy/LazyVim/lua/lazyvim/config/keymaps.lua:119>
```
I am on latest `Lazyvim` update with Rust extra `lang` enabled (no manual tweaking).

**Comment by Verisana** [comment] 2024-01-24 15:35
Yeah, seems like related.

As of temporary workaround, I disabled extra rust:
```
-- { import = "lazyvim.plugins.extras.lang.rust" },
```
And enabled new plugin separately:
```
return {
  {
    "simrat39/rust-tools.nvim",
    enabled = false,
  },
  {
    "mrcjkb/rustaceanvim",
    version = "^3", -- Recommended
    ft = { "rust" },
  },
}
```

It fixed the issue on my side for now. Hope you can replace `rust-tools` soon :pray:

**Comment by dpetka2001** [comment] 2024-01-24 15:37
@Verisana I don't have anything to do with the project. Just a simple user like you who tries to help. I'm sure the maintainer of the project will look into this when he has time. There's also an open PR that tries to do that. All that remains is for it to be merged.

**Comment by folke** [comment] 2024-03-22 08:29
closing this since we now use rustaceanvim

**Closed by folke** 2024-03-22 08:29 UTC
Labels: bug
