### ISSUE TITLE
bug: Enabling mini-animate occasionally causes snippets in C++ to malfunction.

### ISSUE THREAD

**Issue by shininome** [LazyVim/LazyVim#1472] opened 2023-09-20 09:26 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.5

### Describe the bug

https://github.com/LazyVim/LazyVim/discussions/1468

### Steps To Reproduce

1. use ctrl o jump back
2. write some snippet

### Expected Behavior

I'm not sure if this is a bug with mini-animate or an error in the configuration.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
{import = "lazyvim.plugins.extras.ui.mini-animate"}

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2023-09-20 10:51
I read the Discussion that you opened as well as this issue, and in my personal opinion I believe this is an issue with `mini.animate` and not Lazyvim configuration itself. I tried with both `{import = "lazyvim.plugins.extras.ui.mini-animate"}`, which uses the Lazyvim configuration, and the following in `/lua/plugins/animation.lua`
```lua
return {
  {
    "echasnovski/mini.animate",
    opts = {},
  },
}
```
which should be using the default configuration `mini.animate` provides. The issue happens in both tests. This is why I believe the issue lies with `mini.animate` itself, but not 100% sure. I also tried with another user's configuration, which is a custom config and not a distro (user is MariaSolOs, whom I believe is doing an awesome job in Neovim ecosystem) and you can find her dotfiles [here](https://github.com/MariaSolOs/dotfiles/tree/main/.config/nvim) and the same behavior persisted when I installed `mini.animate`, which by default isn't installed in her dotfiles.

**Comment by abeldekat** [comment] 2023-09-20 12:06
@dpetka2001,

Perhaps its possible to compile a minimal repro using LazyVim, disabling all plugins not required for this issue. That will also be useful when creating an issue in `mini.animate`.

Could you have a look at the code below? The correct lspserver needs to be added, and some other plugins might not be needed. Even the lsp might not be needed.

minimal.lua:
```
-- a minimal repro using LazyVim, conditionally enabling plugins by keyword
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

local lsp_extra_servers = {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      -- add server here
    },
  },
}

-- the plugin to test, see extra.ui.mini-animate, without the opts
local plugin_animate_default = {
  "echasnovski/mini.animate",
  event = "VeryLazy",
  config = true,
}

-- stock lazyvim contains 48 plugins, filtering disables 31 plugins
-- adding mini.animate.
local plugins_by_keyword = {
  "lazy.nvim",
  "LazyVim",
  "tokyonight",
  "mini.animate",
  "snip", -- all snippet plugins
  "cmp", -- all cmp plugins
  "lsp", -- all lsp plugins
  "treesitter", -- all treesitter plugins
  "plenary",
  "neodev",
  "neoconf",
  "mason",
  "null_ls",
}
local function conditionally_enable(plugin)
  local plugin_name = string.lower(plugin.name)
  for _, keyword in ipairs(plugins_by_keyword) do
    if plugin_name:find(keyword, 1, true) then
      return true
    end
  end
  return false
end

local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  lsp_extra_servers,
  plugin_animate_default,
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  -- inspect all plugins, and enable conditionally:
  defaults = {
    cond = conditionally_enable,
  },
})
vim.cmd.colorscheme("tokyonight")
```

**Comment by dpetka2001** [comment] 2023-09-20 13:24
@abeldekat I created a minimal repo that reproduces the issue at https://github.com/dpetka2001/lazy_nvim. It's just a minimal config with just `lazy.nvim` and following plugins. I tried to keep it as bare as minimum, since I wanted to see if it was reproducable outside of Lazyvim, thus ensuring that Lazyvim configuration has nothing to do with it. In `plugins` folder only `animate.lua` and `completion.lua` are necessary. `editor.lua` was just for my personal preference while creating this. No LSP is needed. Only `nvim-cmp` and `Luasnip` with `friendly-snippets` are necessary to reproduce this. Pls test it out with the steps provided by @shininome to double check if it's also reproducable for you.

**Comment by dpetka2001** [comment] 2023-09-20 18:11
@shininome Reporting back from the corresponding issue at [mini.nvim](https://github.com/echasnovski/mini.nvim/issues/484) and after echasnovski mentioned his Neovim version he used and was unable to reproduce the issue, I also updated my Neovim (which was built 3 weeks ago when I started trying to reproduce the issue you had and could successfully reproduce it with the minimal repro that I linked in a previous post of mine) to the latest HEAD built from source and cannot reproduce any more. It looks like this was an upstream Neovim issue (that somehow affected `mini.animate`?) and is not happening any more. I don't believe it has anything to do with Lazyvim, thus suggest the issue be closed if you would be kind.

**Comment by abeldekat** [comment] 2023-09-20 18:29
@dpetka2001,

Well done!
As discussed, I will also add the `minimal.lua` using `LazyVim`. The config conditionally enables the required plugins needed to reproduce the issue.

`minimal.lua`:
```lua
-- a minimal init using LazyVim, conditionally enabling plugins by keyword
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- stylua: ignore start
local enabled_plugins_by_lowercase_keyword = {
  "lazy", "tokyo", "animate", "snip", "nvim-cmp"
}
-- stylua: ignore end

local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", version = "6.3.0", import = "lazyvim.plugins" },
  -- stylua: ignore start
  -- overwrite the explicit cond in lazyvim.plugins.lsp
  { "hrsh7th/cmp-nvim-lsp", cond = function() return false end, },
  -- stylua: ignore end
  -- adding: mini.animate
  { "echasnovski/mini.animate", event = "VeryLazy", config = true },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  defaults = {
    cond = function(plugin)
      local plugin_name = string.lower(plugin.name)
      for _, keyword in ipairs(enabled_plugins_by_lowercase_keyword) do
        if plugin_name:find(keyword, 1, true) then
          return true
        end
      end
      return false
    end,
  },
})
vim.cmd.colorscheme("tokyonight")
```

`./.repro/config/nvim/lazylock.json`:
```lua
{
  "LazyVim": { "branch": "main", "commit": "a72a84972d85e5bbc6b9d60a0983b37efef21b8a" },
  "LuaSnip": { "branch": "master", "commit": "8efa4e402a24df6a4713a2ec653147c49e8f73de" },
  "cmp_luasnip": { "branch": "master", "commit": "18095520391186d634a0045dacaa346291096566" },
  "friendly-snippets": { "branch": "main", "commit": "ebf6d6e83494cdd88a54a429340256f4dbb6a052" },
  "lazy.nvim": { "branch": "main", "commit": "2a9354c7d2368d78cbd5575a51a2af5bd8a6ad01" },
  "mini.animate": { "branch": "main", "commit": "230140aa0b06af87c9d345573aab1aaf50d8b539" },
  "nvim-cmp": { "branch": "main", "commit": "5dce1b778b85c717f6614e3f4da45e9f19f54435" },
  "tokyonight.nvim": { "branch": "main", "commit": "9a01eada39558dc3243278e6805d90e8dff45dc0" }
}
```

**Comment by folke** [comment] 2023-09-20 19:30
This may have been fixed by https://github.com/neovim/neovim/pull/24811

I've encountered a similar issue with animations in edgy.nvim. See my original issue here https://github.com/neovim/neovim/issues/23888

Closing this, since it's no longer reproducible on the latest Nightly and is not really a LazyVim issue anyway.

**Closed by folke** 2023-09-20 19:30 UTC
Labels: bug

**Comment by abeldekat** [comment] 2023-09-21 06:38
@dpetka2001 and I discovered that the issue might be related to the `scrolloff` setting and `mini.animate`.

The `scrolloff` setting in `LazyVim`'s `lazyvim.config.options`:
> opt.scrolloff = 4 -- Lines of cont

When using the default [`scrolloff`](https://neovim.io/doc/user/options.html#'scrolloff') and `mini.animate`, the problem does not occur.

See this comment in the issue in [mini.animate](https://github.com/echasnovski/mini.nvim/issues/484#issuecomment-1728497299)

@shininome,

You can reproduce the issue when using the steps and the code snippet provided in that comment:
- save as minimal.lua, in the same folder as where your init.lua is located
- run `nvim -u minimal.lua` in that folder
- restart after installation
- run `nvim -u minimal.lua <file_to_test>`

**Comment by echasnovski** [comment] 2023-09-21 11:54
This particular case seems to be indeed the result of weird combination of issues in both 'mini.animate' and 'LuaSnip'. I've addressed this as much as I deemed it reasonable in echasnovski/mini.nvim/issues/484.

**Comment by dpetka2001** [comment] 2023-09-21 11:57
@echasnovski Thank you for the update and prompt response to this issue. Greatly appreciated.
