### ISSUE TITLE
bug: textobject-based tag block selection breaks with mini.ai enabled

### ISSUE THREAD

**Issue by idnsunset** [LazyVim/LazyVim#1413] opened 2023-09-04 09:05 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Ubuntu 20.04

### Describe the bug

With `mini.ai` enabled, textobject-based tag selection in XML file selects unexpected area but not the text between the pair of tags **that contain underscore**.

### Steps To Reproduce

1. Open a XML file
2. Move the cursor to any text between a pair of tags that contain underscore, e.g. `<first_name>First Name</first_name>` 
3. Press `vit`

### Expected Behavior

The text between the pair of tags gets selected.

**Comment by madjxatw** [comment] 2023-09-04 14:04
Hi, @abeldekat, looks pretty similar. If it is confirmed a bug of mini.ai, this plugin would better be disabled by default.

**Comment by abeldekat** [comment] 2023-09-04 15:03
I also think the issue should be registered in `mini.ai`. 

I don't think the plugin should be disabled by default, as @madjxatw suggested. There are several ways to disable the plugin on a per buffer/ per filetype basis, described [here](https://github.com/echasnovski/mini.nvim/blob/3a3e19d7b7850e711485b8adde73ba44789f2cf6/doc/mini.txt#L270).

For example, a user can create file `after/ftplugin/xml.lua`, containing:

``` lua
vim.b.miniai_disable = true
```

**Comment by abeldekat** [comment] 2023-09-04 15:17
@madjxatw 

In my opinion, this is not a buggy plugin. Its limitations are clearly defined in the docs. See also this [comment](https://github.com/echasnovski/mini.nvim/issues/156#issuecomment-1308429031).

**Comment by dpetka2001** [comment] 2023-09-04 15:31
As @abeldekat noted, the maintainer of the plugin himself has clarified his position as to expect certain false positives since Lua pattern regex engine is quite limited. This is due to the language not being able to offer the more granual control as other languages offer in regards to regex engines. You are welcome to open an issue at the plugin's repo to ask the maintainer if something more can be done in order to solve this issue. Asking to disable this plugin is also a valid opinion of yours, but it's up to the maintainer of Lazyvim to decide on this since he has more experience in regards to Neovim and its ecosystem programming environment. You can easily just disable the plugin in your own configuration if it doesn't meet your needs. Simple as that.

**Comment by madjxatw** [comment] 2023-09-04 15:47
A framework that are supposed to work out of box should not bring wrong and unexpected behaviors, not every one has time or is experienced enough to dig into the configuration. The introduction of a third-party plugin with obvious limitation that leads to errors should be documented or even be replaced. I’ve never asked anyone to disable it but only suggested it be disabled. Just because I could simply solve this issue by myself doesn't mean I have no right to speak out my opinion on this issue.

**Comment by dpetka2001** [comment] 2023-09-04 15:49
Who said anything about you not having any right to speak out your opinion? I stated in my previous comment that your opinion is perfectly valid and in the end it's up to the maintainer of Lazyvim to decide what to do. Where exactly were you offended?

**Comment by madjxatw** [comment] 2023-09-04 15:50
My definition of a bug is different from some else, that's all.

**Comment by abeldekat** [comment] 2023-09-09 09:11
Quoting my reply to @madjxatw:
> I don't think the plugin should be disabled by default, as @madjxatw suggested

For completeness: I changed my mind. My preference would be to have treesitter-textobjects fully configured in the core of LazyVim, and *opt-in* to mini.ai in extras.

Mini.ai is a high quality, powerful plugin. However, "it enhances some builtin textobjects".
There are benefits to this approach, but also some disadvantages, as [stated](https://github.com/echasnovski/mini.nvim/issues/156#issuecomment-1308429031) by the author.

I was considering a pull request for `LazyVim`, preventing mini.ai from taking over the `tag` textobject:
``` lua
{
    "echasnovski/mini.ai",
    enabled = false,
    opts = function(_, opts)
      opts.custom_textobjects = {
        t = false, -- fallback to neovim for tags
      }
    end,
}
```
That would fix this issue, and also the issue referenced [here](https://github.com/LazyVim/LazyVim/issues/1413#issuecomment-1705238732)

However, there might be more enhancements up for debate. As an example, consider:

`local msg = "hello world"`

Position the cursor on the "w", and press `vi"`. Now, the cursor is positioned on the first word, the letter "h". Without mini.ai, the cursor would be positioned on the last word, the letter "d".

**Comment by dpetka2001** [comment] 2023-09-09 10:16
@abeldekat What you're suggesting is another topic overall. As far as this issue is concerned you can look at the code [here](https://github.com/echasnovski/mini.ai/blob/7ae226f331885e6f30e9a8229e113debc59308ae/lua/mini/ai.lua#L1082) for how the `tag` is defined. It only considers alphanumeric characters for the tag's name. I would imagine that the author only took into consideration the naming conventions for `html` tags and not `xml` where underscores are allowed. I don't know if it could be easily extended for taking into consideration `xml` tags naming convention (I believe it could by changing the lua pattern to include underscores but am unsure if this could cause additional complications to the behavior of the plugin). Still this issue should be opened in the `mini.ai` repo and maybe it could be resolved. Why are you passing `opts` since you're disabling `mini.ai` in your snippet?

**Comment by abeldekat** [comment] 2023-09-09 12:19
@dpetka2001, 

Disabling mini.ai in my snippet, that's a typo which I will correct. Thanks!
I gave an opinion in earlier comments. That's the only reason I wrote down my new thoughts.

I still agree that the issue should be opened in the `mini.ai` repo.

**Comment by dpetka2001** [comment] 2023-09-09 12:29
@abeldekat I totally agree with your opinion. For clarification, I have also disabled `mini.ai` and prefer treesitter's text-objects and if you make a PR for moving `mini.ai` to extras I'm totally for it since I don't use it anyway since some time. What rubs me wrong in this specific case, is disregarding the work that an author puts in by calling the plugin buggy (as if every software doesn't have any bugs and works exactly as the users expect) and not making an effort to open an issue at the plugin's repo in case it could be fixed.

**Comment by abeldekat** [comment] 2023-09-09 12:47
@dpetka2001,

I will open the issue in the `mini.ai` repo. 
Regarding the 'buggy' word, I agree completely. However, I would say, let bygones be bygones in that regard.

In case Folke agrees, I would be happy to provide a pr.

**Comment by abeldekat** [comment] 2023-09-09 13:14
I created the [issue](https://github.com/echasnovski/mini.nvim/issues/474) in `mini.ai`'s repo.

**Comment by echasnovski** [comment] 2023-09-09 14:47
> I created the [issue](https://github.com/echasnovski/mini.nvim/issues/474) in `mini.ai`'s repo.

And I [closed it](https://github.com/echasnovski/mini.nvim/issues/474#issuecomment-1712526964). Tag textobject in 'mini.ai' was never intended as a full proof way to select tags, but more as a (fairly limited) enhancement of built-in textobject. For more accuracy I'd suggest using queries from 'nvim-treesitter-textobject' as described in the comment.

------

> ... for me a plugin is not buggy only if at worst it just doesn't work on its own without breaking other normal functionalities. In this case, if pressing `vit`/`dit`/`cit` does nothing rather than operating on wrong selection, then I could consider it as a limitation.

Operating on the side of caution and do nothing instead of doing something wrong **was** the idea here. And leads to less annoying surprises in my opinion.

**Comment by abeldekat** [comment] 2023-09-09 20:22
An update regarding the issue in [`mini.ai`](https://github.com/echasnovski/mini.nvim/issues/474):

@echasnovski discovered that the `nvim-treesitter-textobjects` plugin does not have queries for the ['xml'](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/tree/master/queries) filetype.

Thus, the following will not fix the issue at hand:

`after/ftplugin/xml.lua`:

```lua
local spec_treesitter = require('mini.ai').gen_spec.treesitter
vim.b.miniai_config = {
  custom_textobjects = {
    t = spec_treesitter({ a = '@function.outer', i = '@function.inner' }),
  },
}
```

He created a [PR](https://github.com/abeldekat/test_mini_ai/pull/1) in the repository I provided in order to reproduce the problem, containing the necessary query:

`after/queries/xml/textobjects.scm`:

```
(element (content) @function.inner) @function.outer
```

Many thanks, @echasnovski!

**Comment by dpetka2001** [comment] 2023-09-09 20:43
Tnx for the update @abeldekat. Very diligent as always :smile: 
And I really loved your interactions and inspirational talk at `mini.ai`'s issue as well. Keep up the good work.

**Comment by abeldekat** [comment] 2023-09-10 09:55
Hi @dpetka2001,

I created the [PR](https://github.com/LazyVim/LazyVim/pull/1434) for `LazyVim`.

**Comment by echasnovski** [comment] 2023-09-10 10:23
Moving a full plugin to extras only because it doesn't work for special cases of tag textobject is a *bit too much*. 'mini.ai' provides a lot more than just enhanced built-in textobjects. Fixing particular textobjects users don't like is the correct path here.

Positioning cursor on the start of selection makes it more aligned with how it is done when applied an operator. See the paragraph after `:h operator-doubled`.

**Comment by abeldekat** [comment] 2023-09-10 10:44
Hi @echasnovski,

This PR is not about moving the plugin because of the special cases and the preferences of users.
In the end, the main motivation *is* the enhanced builtin textobjects, because they change core builtin functionality. 

In my *personal* opinion, for a setup like `LazyVim`, that should be opt-in.
This PR can still be refused by Folke. I would understand that.

Just to emphasize: I created this PR *and* I think it's a great plugin.

**Comment by echasnovski** [comment] 2023-09-10 10:58
The "If plugin changes built-in functionality then it should be opt-in" statement casts a very broad net: most of UI ones ('noice.nvim', 'nvim-notify', 'bufferline.nvim', 'lualine.nvim', 'which-key.nvim'), 'flash.nvim',some other editing ones ('mini.pairs'), even 'lazy.nvim' itself. I can not disagree more with this.

Yes, sure, Folke is the one to decide here when he returns.

**Comment by dpetka2001** [comment] 2023-09-10 11:59
I honestly don't know what the correct solution would be in this case, as it seems to me like both sides have their own merit. In the end, it's really easy for anyone to disable any plugin they want in their personal spec. Let us wait for Folke's decision on this, whatever it may be without bad feelings about the outcome.

**Comment by abeldekat** [comment] 2023-09-10 17:39
@dpetka2001, thanks!

@echasnovski, please allow me to rephrase the following line:
> In the end, the main motivation is the enhanced builtin textobjects, because they change core builtin functionality.

I did not intend to cast a very broad net.
That line should be:

In the end, the main motivation is the enhanced builtin textobjects, because of the changes to the core behavior of `neovim`'s `textobjects`. In my personal opinion, for a setup like LazyVim, that should be opt-in.

**Comment by abeldekat** [comment] 2023-09-12 18:24
Hello @echasnovski,

I implemented another [approach](https://github.com/LazyVim/LazyVim/pull/1444) as well, only disabling the `tag textobject` defined in `mini.ai`.
Your input would be highly appreciated!

**Comment by abeldekat** [comment] 2023-09-12 20:11
Hi @echasnovski,

Thanks for the feedback!
As discussed, for the tree-sitter route, a PR is needed for plugin `nvim-treesitter-textobjects`, providing an `xml` query.

I am wondering: Why isn't it there already? I noted that queries for `json` are also not present. I see a lot of programming languages, but no "data specifications", like `json` or `xml`.

I implemented the tree-sitter route as a poc in my [repo](https://github.com/abeldekat/starter/tree/miniai_fix_tag), using a `lazyvim starter`, adding the `query` and the `t` textobject. 
`LazyVim`'s `treesitter` spec also needed to be extended to always install `xml` 
 
File `test.xml`, `vit`, now works as expected.

But, as `xml` is a data specification, it will occur and be manipulated in other `filetypes` as well.

`test_contains_xml.lua`:

```lua
local M = {}

M.use_xml_inside_lua = function()
  vim.print("Containing xml: <first_name>First Name</first_name>")
end

return M
```

Now, the same `vit` selects the whole line. Default behaviour: "first name"

If this inconsistency cannot be tackled, perhaps doing nothing for the `tag textobject` is a better approach, allowing the user to weigh the benefits and downsides of opting-in to that part of `mini.ai`.

I hope you are willing to once again provide feedback, and correct any errors in my reasoning!

**Comment by echasnovski** [comment] 2023-09-13 07:36
> But, as `xml` is a data specification, it will occur and be manipulated in other `filetypes` as well.

Yes, the downside of tree-sitter route is that it doesn't work in strings and comments. If that is a concern, there is also (first suggested solution in my linked comment) a more refined specification for tag text object to also respect punctuation in tag name.

**Closed** 2023-09-26 12:16 UTC
Labels: bug

**Comment by folke** [comment] 2023-09-26 12:19
`mini.ai` is one of the **best** Neovim plugins out there so it will stay as a core LazyVim plugin.

I just pushed an update with the more accurate lua pattern for tags as provided by @echasnovski
This solves op's issue. I've looked into using treesitter instead, but that's not really doable at this point, since nvim-treesitter-text-objects does not provide objects for tags.

**Comment by echasnovski** [comment] 2023-09-26 12:29
> I just pushed an update with the more accurate lua pattern for tags as provided by @echasnovski This solves op's issue. I've looked into using treesitter instead, but that's not really doable at this point, since nvim-treesitter-text-objects does not provide objects for tags.

Technically it seems to use [`@function.outer` and `@function.inner`](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/bd103502252027434ec42f628d2dbf54821d4ce6/queries/html/textobjects.scm#L1-L3) for those in appropriate languages.

**Comment by folke** [comment] 2023-09-26 12:57
For some it could work, but it didnt work well for tsx etc.

Besides, `function,outer` and inner is already mapped in `mini,ai` to `af` and `if`, so a user can use that instead of `it` and `at`
