### ISSUE TITLE
bug: make nvim-window-picker compatible with lazyvim

### ISSUE THREAD

**Issue by ikonitas** [LazyVim/LazyVim#2305] opened 2024-01-04 18:10 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS

### Describe the bug

Not being prompts to pick a window and returns the window id of the picked window

### Steps To Reproduce

1. Open a few splits and files
2. Run `lua require('window-picker').pick_window()` nothing happens

### Expected Behavior

To be able to pick the window and return to the picked window

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"folke/LazyVim",
	-- add any other plugins here
	{
		"s1n7ax/nvim-window-picker",
		name = "window-picker",
		event = "VeryLazy",
		version = "2.*",
		config = function()
			require("window-picker").setup()
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by abeldekat** [comment] 2024-01-04 18:30
This is not a bug in LazyVim. LazyVim does not provide a config for nvim-window-picker.

Please ask questions in the discussions forum.
Kindly close this issue.

**Closed** 2024-01-04 18:53 UTC
Labels: bug
