### ISSUE TITLE
bug: restoring a session opens netrw

### ISSUE THREAD

**Issue by prurph** [LazyVim/LazyVim#2036] opened 2023-11-18 00:40 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macOS Sonoma 14.1.1

### Describe the bug

Opening LazyVim and selecting "restore session" appears to open netrw in a separate buffer, causing it to appear in the bufferline. Confusingly, if one navigates to this buffer, hotkeys to move to other buffers (`<S-h>`, `<S-l>`), do not work, and one must use `:q` or `<leader>bd` to close it. This happens whether or not the NeoTree window was open at the time of session saving/quitting LazyVim.

Ideally, the NeoTree state could be stored and restored as part of the session, but barring that it seems less than ideal to open this extra explorer.

### Steps To Reproduce

1. Open LazyVim and load some files
2. Exit LazyVim
3. Reopen LazyVim and select "restore session"
4. Observe the extra buffer created in the bufferline, as pictured below on the far right (first image)
5. When selected, the window disappears from the bufferline (second image) and so must be closed with `:q` or equivalent

<img width="741" alt="image" src="https://github.com/LazyVim/LazyVim/assets/6109531/3d826a14-a32e-4d0e-8717-765e500ff444">

<img width="1010" alt="image" src="https://github.com/LazyVim/LazyVim/assets/6109531/c3da4985-cc09-4772-9670-0ca76353c825">

### Expected Behavior

Sessions should not open netrw when restoring.

### Repro

```Lua
Reproducible with unmodified LazyVim starter.
```

**Comment by prurph** [comment] 2023-11-18 03:00
Embarrassingly/happily I am unable to reproduce this now after doing some further tinkering.

**Comment by dpetka2001** [comment] 2023-11-18 10:55
Not able to reproduce this. If you can provide more concrete info on how to reproduce, that would be helpful. If this was a one time thing and you're not able to reproduce either, you might consider closing this issue.

**Closed** 2023-11-18 12:55 UTC
Labels: bug
