### ISSUE TITLE
bug: Double descs for `around/inside` objects?

### ISSUE THREAD

**Issue by dpetka2001** [LazyVim/LazyVim#233] opened 2023-02-10 16:54 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

neovim-0.9.0~ubuntu1+git202302091604-2af31fc50-333b5866f

### Operating system/version

Linux Mint 21.1

### Describe the bug

After latest upgrade of `LazyVim` with the better descriptions for `mini.ai` there appear 2 entries in the `which-key` menu when you press for example `v` to visually select an object. 2 entries for `a -> +around` and `i -> inside`. I would expect the entries to be merged? Not sure what's happening.

### Steps To Reproduce

1. Press `v` for visually selecting object.
2. `Which-key` menu appears with 2 entries for `a -> +around` and `i -> inside`

### Expected Behavior

I would expect to see only one entry in `which-key` menu.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2023-02-10 17:02
Duplicate of https://github.com/folke/which-key.nvim/issues/267

**Comment by folke** [comment] 2023-02-10 17:16
Fixed by merging that PR

**Closed by folke** 2023-02-10 17:16 UTC
Labels: bug, upstream
