### ISSUE TITLE
bug: Folke is a beast. 

### ISSUE THREAD

**Issue by WillEhrendreich** [LazyVim/LazyVim#1644] opened 2023-10-09 16:59 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

all

### Operating system/version

any

### Describe the bug

I'd like to make a formal complaint that folke does not get enough damn recognition.. 

I come in from the weekend, and see something like 60 updates just on lazy.nvim and lazyvim alone. 

Dude... 

I'm so absolutely grateful to you for how much you support the community. Seriously man, you could just sit back and rest on the already huge mountain of work, but no, you just continue to do so freaking much all the time, for no reason other than your sincere desire to support everyone else. 

It's obnoxiously awesome. 

Thank you. 

### Steps To Reproduce

1. Be Folke
2. Have a genuine passion to help the neovim community by making fantastic contributions all the time
3. Make those contributions
4. .. get thanked.. but not nearly as much as you deserve. 

see the problem? It's a problem. 

### Expected Behavior

That more people would shout out @folke and say what a chad he is. 

### Repro

```Lua
-- I have never seen this reproduced, I'm not sure how one would. 

thanks. :)
```

**Comment by folke** [comment] 2023-10-09 18:25
Thanks a lot! :)

Since this is not reproducible, I'll close it for now ;)

**Closed by folke** 2023-10-09 18:25 UTC
Labels: bug

**Comment by NeckBeardPrince** [comment] 2023-10-11 17:49
> Thanks a lot! :)
> 
> Since this is not reproducible, I'll close it for now ;)

Though, you might want to slow down on the release numbers. Two weeks ago, you were on `6.4.3` and already about to hit `10.0.0`. You're going to run out of numbers in about two months, lol.
