### ISSUE TITLE
bug: Unable to restore the maximized Neo-tree window

### ISSUE THREAD

**Issue by mkdir700** [LazyVim/LazyVim#3429] opened 2024-06-03 02:05 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 20.04

### Describe the bug

This feature is submitted here https://github.com/LazyVim/LazyVim/commit/3ace8277e54370c0aa3d17e61018cf039c42d69b

I can't use a shortcut to restore the maximized Neo-tree window.

### Steps To Reproduce

1. Open Neo-tree
2. Focus on the Neo-tree window
3. Maximize the Neo-tree window using a shortcut key
4. Press the shortcut key again to try to restore.

### Expected Behavior

I hope to restore the Neo-tree window when I press the shortcut key again. this works in other windows, but not in Neo-tree.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "nvim-neo-tree/neo-tree.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-06-03 07:11
Duplicate of #3396.

**Closed** 2024-06-03 07:21 UTC
Labels: bug
