### ISSUE TITLE
bug: lua completion is very slow in init.lua

### ISSUE THREAD

**Issue by xzbdmw** [LazyVim/LazyVim#2370] opened 2024-01-17 21:22 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Macos 14.2

### Describe the bug

just default setting compared to default lunarvim,t ryed go and rust both is fast.
lazyvim:

https://github.com/LazyVim/LazyVim/assets/97848247/11679b6e-9739-4324-a55b-ae2b1dbf7b66

lunarvim:

https://github.com/LazyVim/LazyVim/assets/97848247/34babf33-3a08-418e-9f67-2dde31711f51

### Steps To Reproduce

default lsp settings

### Expected Behavior

after type dot, completion list instant open

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2024-01-17 23:30
Change in `~/.config/nvim/.neoconf.json` 
```lua
"neodev": {
    "library": {
      "enabled": true,
      "plugins": false
    }
  },
```
This imitates the Lunarvim behavior.

**Comment by xzbdmw** [comment] 2024-01-18 14:16
This don't change the laggy after I type `vim. `, seems when I type dot there is something stopping lua_ls from trigger completion.

**Comment by dpetka2001** [comment] 2024-01-18 15:07
It does change it for me. Show the contents of your `.neoconf.json`. Also a link to your dotfiles would be helpful.

**Comment by xzbdmw** [comment] 2024-01-19 14:33
``` {
    "neodev": {
        "library": {
            "enabled": true,
            "plugins": false
        }
    },
    "neoconf": {
        "plugins": {
            "lua_ls": {
                "enabled": true
            }
        }
    }
}
```

**Comment by dpetka2001** [comment] 2024-01-19 16:09
A link to your dotfiles would be helpful to see if there's something else. You're not really giving a reproducible situation without them.

**Comment by folke** [comment] 2024-01-19 16:22
Either you get completions for all plugins, but completion can be slow on older hardware (which is LazyVim's default setup), or you disable completion for plugins and completion should be faster.

Closing this, since either way, this is not  a LazyVim issue, but a limitation on how Lua LS works.

**Closed by folke** 2024-01-19 16:22 UTC
Labels: bug

**Comment by xzbdmw** [comment] 2024-01-19 19:11
> It does change it for me. Show the contents of your `.neoconf.json`. Also a link to your dotfiles would be helpful.

here is my nvim folder, I tested it with default lazyvim and disable plugin still quit slow, my computer is not bad

**Comment by dpetka2001** [comment] 2024-01-19 19:28
[Screencast 2024-01-19 21:27:10.webm](https://github.com/LazyVim/LazyVim/assets/12776461/5af961b3-aa69-4bc7-9a14-0946e3e50be1)
I cloned your repo and tried your configuration and observed no lag as also shown in the video. Might be your computer. Don't know what to tell you.

**Comment by xzbdmw** [comment] 2024-01-20 00:42
> [Screencast 2024-01-19 21:27:10.webm](https://github.com/LazyVim/LazyVim/assets/12776461/5af961b3-aa69-4bc7-9a14-0946e3e50be1) I cloned your repo and tried your configuration and observed no lag as also shown in the video. Might be your computer. Don't know what to tell you.

I see difference in right butttom info showing that diagnose and processing completion but your screen dont show that, so strange.

https://github.com/LazyVim/LazyVim/assets/97848247/82e4df5f-8fcd-4769-b60c-ebc2da6a40fe

**Comment by xzbdmw** [comment] 2024-01-21 14:13
And only in my ~/.config/nvim dictionary completion is slow. If I open a plugin repository at `/Users/xzb/.local/share/nvim/lazy/ `such as using `nvim /Users/xzb/.local/share/nvim/lazy/cmp_yanky/lua/cmp_yanky.lua`, completion is very fast and from that entry point if using fuzz find to open my own config dictionary everything is smooth, and if I using `nvim ~/.config/nvim` directly it is slow again , even after that I open repository file, still very laggy. I wander why would be that and very confused.

**Comment by xzbdmw** [comment] 2024-01-21 23:31
OK, the .neoconf.json file in nvim dictionary can't be recognized by neoconf, only after I changed the name to neoconf.json(under ~/.config/nvim) to make it a global config file my setting works.
