### ISSUE TITLE
feature: docstring comment snippets with blink.cmp

### ISSUE THREAD

**Issue by idnsunset** [LazyVim/LazyVim#5243] opened 2024-12-24 04:11 UTC
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

After switching to `blink.cmp`, I no longer get the docstring comment snippets completion, e.g. doxygen style c++ docstring completion while editing a cpp file. With `nvim-cmp`, this is done by the `extended_filetypes` configuration option of the `nvim-snippets` plugin, but there seems no way to easily enable this with `blink.cmp`.

### Describe the solution you'd like

Trigger docstring snippet completion on configured filetypes when typing the comment sign, e.g. typing `/*` triggers the c++ docstring snippet completion as `nvim-cmp` does.

### Describe alternatives you've considered

I've just switched back to using `nvim-cmp`.

**Comment by dpetka2001** [comment] 2024-12-24 09:16
`blink` also has a `opts.sources.providers.snippets.opts.extended_filetypes` setting, so you probably can use that. Please read the [blink docs](https://cmp.saghen.dev/configuration/reference.html#sources) for further info.

**Comment by idnsunset** [comment] 2024-12-24 13:29
I have the following in my `blink.cmp` configuration, unfortunately it doesn't work.

```lua
opts = {
  -- ...
  sources = {                                                        
    -- Any nvim-cmp sources added to `compat` will be enabled by blin
    compat = {},                                                     
    default = { "lsp", "path", "snippets", "buffer" },               
    cmdline = {},                                                    
    providers = {                                                    
      snippets = {                                                   
        opts = {                                                     
          friendly_snippets = true,                                  
          search_paths = { vim.fn.stdpath("config") .. "/snippets" },
          global_snippets = { "all" },                               
          extended_filetypes = {                                     
            c = { "cdoc" },                                          
            cpp = { "cppdoc" },                                      
            lua = { "luadoc" },                                      
            python = { "pydoc" },                                    
            rust = { "rustdoc" },                                    
            sh = { "shelldoc" },                                     
          },                                                         
          ignored_filetypes = {},                                    
          get_filetype = function(ctx)                               
            return vim.bo.filetype                                   
          end,                                                       
        },                                                           
      },                                                             
    },                                                               
  },                                                                 
  -- ..
},
```

**Comment by dpetka2001** [comment] 2024-12-24 13:38
Then make an issue in blink repo. If something is wrong with its `extended_filetypes` it won't get solved here.

**Comment by dpetka2001** [comment] 2024-12-24 13:57
For Lua that I tested including `luadoc` it worked, but with some weird behavior. It seems it doesn't accept `@` or `---` as trigger characters. So, if you want to complete the snippet `@author`, you would have to start writing `auth` and then choose the snippet to complete. You would have to ask about this in blink repo.

**Comment by dpetka2001** [comment] 2024-12-24 14:57
For Lua I managed to include docstrings with the following configuration
```lua
opts = {
  completion = {
    keyword = {
          -- range = "prefix",
          -- Regex used to get the text when fuzzy matching
          regex = "[-_@]\\|\\k",
          -- After matching with regex, any characters matching this regex at the prefix will be excluded
          exclude_from_prefix_regex = "[\\.]",
    },
  },
},
```
The original `exclude_from_prefix_regex = '-'` which exludes the character `-` from matching into the regex after the first `-` is typed. Not sure what the best approach should be. The maintainer of blink will surely know more about this than me. For cpp docsnippets, maybe you could add `regex = "[/-_@*]\\|\\k"` and test it out.

**Comment by mdmjmsa** [comment] 2024-12-25 12:56
If the default `exclude_from_prefix_regex` is the root cause for luadoc snippets not to show, what causes the cppdoc snippets not to work?

**Comment by dpetka2001** [comment] 2024-12-25 14:20
I believe it's the `regex` itself. Try adding `regex = "[/-_@*]\\|\\k"` and see if it works for you. For more info you should really inquire at blink repo, as this is just from what I've tried experimenting with and based on my observations.

**Comment by mdmjmsa** [comment] 2024-12-26 12:02
> I believe it's the `regex` itself. Try adding `regex = "[/-_@*]\\|\\k"` and see if it works for you. For more info you should really inquire at blink repo, as this is just from what I've tried experimenting with and based on my observations.

I've seen an issue open in the blink.cmp repo, but the author just replied that he could not reproduce and that seems to imply this kind feature should work after a very small amount of configuration. There seem no other people have encountered the similar issue as mine, so I am suspecting if something is misconfigured.

**Comment by dpetka2001** [comment] 2024-12-26 12:13
Please try the following in your personal blink configuration
```lua
opts = {
  completion = {
  keyword = {
          -- Regex used to get the text when fuzzy matching
          regex = "[/*-_@]\\|\\k",
          -- After matching with regex, any characters matching this regex at the prefix will be excluded
          exclude_from_prefix_regex = "[,]",
        },
  },
},
```
With this I can see the cpp docstring snippets just fine. The only caveat is that when pressing `/*` it doesn't show the completion menu automatically and I have to press `<C-space` to show them.

**Comment by mdmjmsa** [comment] 2024-12-26 12:52
@dpetka2001 , thanks for sharing, but it behaves a bit weirdly. When typing `/*`, nothing comes up, but after I press `Backspace` to remove the `*` char, the snippets pops up.

**Comment by dpetka2001** [comment] 2024-12-26 13:06
Yes that's why i said i also had to press `<c-space>` for the snippets tp show up. My guess is that `/` is also the trigger character for the path source and that may be causing some kind of conflict. Either way maintainer of blink should clarify how to best configure it.

**Comment by dpetka2001** [comment] 2024-12-29 19:39
[Issue upstream](https://github.com/Saghen/blink.cmp/issues/758) has been closed as not planned due to it being already a combination of 2 other open issues. I believe this can be closed here?

**Closed** 2024-12-30 16:02 UTC
Labels: enhancement

**Comment by madjxatw** [comment] 2025-01-01 09:28
An upstream issue does not mean it should be closed without further actions in this repo. `nvim-cmp` should be switched back to be default since `blink.cmp` is still immature.
