### ISSUE TITLE
bug: error when using tab to autocomplete search for certains commands

### ISSUE THREAD

**Issue by ShabirK21** [LazyVim/LazyVim#393] opened 2023-03-07 03:51 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-1139+gba38f35d3e

### Operating system/version

Arch Linux 6.2.2-zen1-1-zen

### Describe the bug

I get "E464: Ambiguous use of user-defined command" when using auto-complete via tabbing in the cmdline for "LspInfo" and "NullLsInfo" but this doesnt happen if I type out the whole command without auto-complete.

### Steps To Reproduce

1. Open cmdline
2. key in "Lsp" or "Null"  
3. press tab to auto-complete for "LspInfo" or "NullLsInfo"

### Expected Behavior

The info page for "LspInfo" or "NullLsInfo" opens up

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2023-03-07 07:04
can't reproduce and also did not provide a repro. closing

**Closed by folke** 2023-03-07 07:04 UTC
Labels: bug
