### ISSUE TITLE
bug: High CPU load with extras/lang/go

### ISSUE THREAD

**Issue by varac** [LazyVim/LazyVim#2033] opened 2023-11-17 07:41 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Manjaro sway edition (rolling release, up to date as of today)

### Describe the bug

When activating the lang/Go extra, Neovim has a high CPU load (currently ~50%) when opening a golang file.
The content of the file doesn't matter, a simple `package main` is enough to trigger this behaviour.
This can get reproduced with a Lazyvim config from scratch.

### Steps To Reproduce

1. Start a fresh LazyVim installation following https://www.lazyvim.org/installation
2. Start neovim and let Lazy install all the things
3. Go to `Extras` and enable `lang.go`, restart neovim
4. Open a golang file
5. CPU usage goes up to 50% (in my case)

### Expected Behavior

CPU usage is comparable to other language servers baseline (i.e. `lang/python`: 1.0% in my case)

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```
```

**Comment by abeldekat** [comment] 2023-11-21 13:58
Hello @varac,

Using your steps, I cannot reproduce that increase.
On my system, the `cpu` usage is negligible.

Neovim: 0.9.4
Go: go version go1.21.4 linux/amd64
Gopls: v0.14.2

Perhaps this is not a `LazyVim` issue.

**Comment by hinricht** [comment] 2023-11-30 12:17
@abeldekat Thanks for testing. I haven't had time to look into this until today and noticed that the issue is not existing anymore. Closing until I reencounter it again.

**Comment by hinricht** [comment] 2023-11-30 12:18
Looks like I can't close the issue.

**Comment by dpetka2001** [comment] 2023-11-30 12:29
Just do a refresh on the page and press `Close issue` again?

**Closed** 2023-11-30 16:31 UTC
Labels: bug
