### ISSUE TITLE
bug: Edgy/Aerial warning

### ISSUE THREAD

**Issue by fredrikaverpil** [LazyVim/LazyVim#1677] opened 2023-10-12 14:02 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Sonoma 14.0

### Describe the bug

I have this in my lazy.lua:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },

    { import = "lazyvim.plugins.extras.ui.edgy" },

    { import = "lazyvim.plugins.extras.lang.docker" },
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.terraform" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.yaml" },

    -- https://www.lazyvim.org/configuration/recipes#use-eslint-for-fix-on-save-and-prettier-for-formatting
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    { import = "lazyvim.plugins.extras.linting.eslint" },

    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.dap.nlua" },

    -- { import = "lazyvim.plugins.extras.coding.copilot" },  -- see ai.lua instead

    { import = "lazyvim.plugins.extras.coding.yanky" },
    { import = "lazyvim.plugins.extras.util.mini-hipatterns" },
    { import = "lazyvim.plugins.extras.util.project" },
    { import = "lazyvim.plugins.extras.vscode" },
    { import = "lazyvim.plugins.extras.editor.mini-files" },
    { import = "lazyvim.plugins.extras.editor.navic" },
    { import = "lazyvim.plugins.extras.editor.aerial" },

    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = false }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})

```

But I still see this everytime I open LazyVim 10.0.0:

```
   Warn  15:50:44 notify.warn LazyVim The `edgy.nvim` extra must be **imported** before the `aerial.nvim` extra to work properly.
```

And Aerial doesn't use edgy.

But if I instead install the extras via `:LazyExtras`, I see no such error and Aerial uses edgy just fine.

### Steps To Reproduce

-

### Expected Behavior

No warning, proper Aerial support when Edgy is imported before Aerial.

**Comment by fredrikaverpil** [comment] 2023-10-12 14:06
@folke I would not mind using `:LazyExtras`. Is there a file somewhere in the installation that defines which extras I have opted to use, that I can add to my dotfiles?

**Comment by folke** [comment] 2023-10-12 15:58
I'm not able to reproduce this.

The order of edgy and aerial in your config file is correct and shows no warnings for me.

Can you reproduce?

**Comment by fredrikaverpil** [comment] 2023-10-12 18:20
It was consistent behavior, always giving me a warning.

In which way would you want me to reproduce it for you?
I've got my entire config and lockfile in git if that helps.

But we can also close this for now if you wish. At least I personally have moved over to using `:LazyExtras`/`lazyvim.json` instead, and no longer seeing this warning because of it.

**Comment by folke** [comment] 2023-10-12 18:26
ok, I'll close it for now an will further investigate in case it pops up again

**Closed by folke** 2023-10-12 18:26 UTC
Labels: bug
