### ISSUE TITLE
bug: Weird symbol/character!!

### ISSUE THREAD

**Issue by sentakuhm** [LazyVim/LazyVim#2146] opened 2023-12-06 11:55 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Arch Linux

### Describe the bug

I tried many nerd fonts and configured fontconfig with fallback fonts as well, everything looks good except this character keep showing idk how to remove it.
![swappy-20231206-123705](https://github.com/LazyVim/LazyVim/assets/25133437/60f3027b-f882-4544-b40b-a3eab268d465)

 

### Steps To Reproduce

1. installed LazyVim.
2. installed some extras from :LazyExtras = dap,lsp,.... this issue appears exactly after enabling lang.rust Extra. 
3. no configuration added except some recipes from documentation page.

### Expected Behavior

i just want this character to disappear from the editor.

**Comment by sentakuhm** [comment] 2023-12-08 16:07
> It seems that you have some kind of transparency. Are you sure it's not something showing from the background?
no its not, i configured terminal to no transparency, but no luck.

**Comment by dpetka2001** [comment] 2023-12-08 16:13
Maybe it's a problem with the fonts you use? Have you tried different fonts?

**Comment by dpetka2001** [comment] 2023-12-09 10:30
I missed reading the part about you trying different fonts, sorry about that. I'm afraid I'm out of ideas, especially since I can't reproduce the issue, as everything looks normal on my end when I enable the `lang.rust` extra, as shown in the picture in my first post.

**Comment by sentakuhm** [comment] 2023-12-09 13:07
> Edit: I imagine your terminal is properly configured to use the fonts that you use, right?

yes, in system fontconfig:
```
<family>monospace</family>
  <prefer>
   <family>JetBrainsMono Nerd Font</family>
   <family>Noto Color Emoji</family>
   <family>Symbols Nerd Font</family>
  </prefer>
```
on Alacritty settings:
```
# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font
  size: 11.0
```

**Comment by dpetka2001** [comment] 2023-12-09 13:45
I'm sorry, but if it's running fine on other terminals (I use kitty and cannot see this issue), then it's definitely a rendering issue. I would suggest switching to another terminal, since the alacritty team doesn't seem to consider this their fault. I don't know whose fault it is, but it definitely is not LazyVim's fault. The terminal uses the font you use to render that icon. That icon is probably provided by `rust-tools` codelens. So, you might want to take it up there if you like.

**Comment by sentakuhm** [comment] 2023-12-09 16:19
i think lts time to go with kitty terminal.

**Comment by abeldekat** [comment] 2023-12-26 16:38
Hi @sentakuhm,

Could you close this issue?

**Closed** 2023-12-26 18:58 UTC
Labels: bug
