### ISSUE TITLE
bug: cursor flash wildly and unexpected behavior of terminal

### ISSUE THREAD

**Issue by lvyuemeng** [LazyVim/LazyVim#4287] opened 2024-08-11 00:57 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

windows 11

### Describe the bug

cursor in Cmdline flash wildly, when access file and exit with :wq, it will prompt a terminal.

### Steps To Reproduce

( my username is non-ascii and therefore I have to toggle `[System.Text.Encoding]::UTF8`. I don't know whether it's related)
(  another hint is the different permissions of nvim and nvim-data because of reinstallation of my system)
follow the installation.
During installation, some error will prompt like `can't find module treesitter, mason` etc. But after restart and sync plugins, all fine except above problem.

### Expected Behavior

No cursor flash wildly and terminal prompt.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  },
})
```

**Comment by dpetka2001** [comment] 2024-08-11 08:41
If you're referring to a problem similar to the one discussed in #4285 then the problem lies with `noice.nvim` and can only be fixed from the side of the plugin itself. If your problem is different please provide more information (preferably some video where it shows what's happening).

**Comment by lvyuemeng** [comment] 2024-08-11 09:44
https://github.com/user-attachments/assets/e7b75fa2-62c9-4789-b433-2b8038d8ccba

Here the problem, I guess it's no relation to what you mentioned. and the other problem is terminal prompt when I access and exit file.

**Comment by dpetka2001** [comment] 2024-08-11 10:04
I think it's the same behavior and it's due to `noice.nvim`. Please open an issue there as this can't be fixed here. Just to test if you still have the same behavior try to disable `noice.nvim` with the following in `~/.config/nvim/lua/plugins/disabled.lua`
```lua
return {
  {
    "folke/noice.nvim", enabled = false,
  },
}
```
If you don't observe the same behavior with the above code snippet, then it is some kind of bug with `noice.nvim`. There are already some open issues at the plugin's github repo about flashing cursor moving wildly, so they might be related.

**Comment by lvyuemeng** [comment] 2024-08-11 11:43
> I think it's the same behavior and it's due to `noice.nvim`. Please open an issue there as this can't be fixed here. Just to test if you still have the same behavior try to disable `noice.nvim` with the following in `~/.config/nvim/lua/plugins/disabled.lua`
> 
> ```lua
> return {
>   {
>     "folke/noice.nvim", enabled = false,
>   },
> }
> ```
> 
> If you don't observe the same behavior with the above code snippet, then it is some kind of bug with `noice.nvim`. There are already some open issues at the plugin's github repo about flashing cursor moving wildly, so they might be related.

you are right, sorry for my misunderstanding. after `disabled.lua`, this problem does disappear. but the problem of terminal prompt is still occur, any hint?

**Comment by dpetka2001** [comment] 2024-08-11 12:52
I don't understand what the problem about terminal prompt means. Can you explain in more detail and show video about what happens?

**Comment by lvyuemeng** [comment] 2024-08-11 14:20
https://github.com/user-attachments/assets/28cbaf5d-8ea3-4547-8403-5b48f0d7f717

here the prompt is the windows cmd. It will occur when I access or :wq, save and exit file.

**Comment by dpetka2001** [comment] 2024-08-11 14:53
I don't know what this is, but it seems to me some kind of artifact with VsCode. Never seen this before. If you can provide specific steps to reproduce this, that would be great, otherwise it really seems unrelated to LazyVim. The only actual problem this bug issue describes, is the one related to `noice.nvim` and for that problem it will have to be solved by the plugin itself, nothing that can be done here.

**Comment by lvyuemeng** [comment] 2024-08-12 09:45
> I don't know what this is, but it seems to me some kind of artifact with VsCode. Never seen this before. If you can provide specific steps to reproduce this, that would be great, otherwise it really seems unrelated to LazyVim. The only actual problem this bug issue describes, is the one related to `noice.nvim` and for that problem it will have to be solved by the plugin itself, nothing that can be done here.

I reinstall again, and at first neovim doesn't pop anything when I access file. I typed some code into keymap.lua. when I save and exit then access file again, problem occured. At first, I thought it was the problem of code, as you said. I delete all code, save and exit again, problem was still there. At least it's not related to vscode.

**Comment by lvyuemeng** [comment] 2024-08-12 09:54
I deleted all file and folder except `Lazy` folder. then problem disappeared, I guess it's due to somehow improper initialization?

**Comment by dpetka2001** [comment] 2024-08-12 09:57
If you deleted all folders except Lazy in nvim-data, that means it's something in your personal configuration that causes it.

**Comment by lvyuemeng** [comment] 2024-08-12 10:01
> If you deleted all folders except Lazy in nvim-data, that means it's something in your personal configuration that causes it.

Strangely, I recover all back-up in `nvim` and no problem occur,  I thought it may certain vscode extensions toggle something, but still no problem when I open vscode.

**Comment by dpetka2001** [comment] 2024-08-12 10:05
I don't know what to tell you, since I don't use VsCode. I only use Neovim in terminal.

**Comment by lvyuemeng** [comment] 2024-08-12 11:10
I currently found mason initialization is the problem, after it install some lsp about lua (I haven't install any other lsp, so I don't know whether other lsp will do the same effect), the problem occur. Then I delete folder of mason, everything was fine.

**Comment by dpetka2001** [comment] 2024-08-12 11:51
Did you enable the vscode Extra as explained [here](https://www.lazyvim.org/extras/vscode). It only enables a handful of plugins that don't conflict which VsCode.

**Comment by iamxiaojianzheng** [comment] 2024-08-30 03:14
@lvyuemeng  I have encountered all the problems you mentioned. I haven't found a solution yet.

**Comment by iamxiaojianzheng** [comment] 2024-08-30 03:18
> clip.mp4
> Here the problem, I guess it's no relation to what you mentioned. and the other problem is terminal prompt when I access and exit file.

I have the same problem

**Comment by iamxiaojianzheng** [comment] 2024-08-30 04:00
@lvyuemeng look this https://github.com/folke/noice.nvim/issues/923

**Comment by iamxiaojianzheng** [comment] 2024-08-30 06:34
A temporary fix, until folke releases the next version.
https://github.com/folke/noice.nvim/pull/937/commits/5e6278c44112d8772a5d9ff282f53f07c383bd20

**Comment by vricop** [comment] 2024-08-31 14:56
Others, me included have noticed this happens when opening neovim inside zellij/neovim.

**Comment by folke** [comment] 2024-09-18 06:46
That's not a noice bug. Noice does what it should do. 
The linked issue is something that should be fixed in Neovide.

In TUI, I also don't see the flickering at all, so make sure you use a recent NEovim built

**Closed by folke** 2024-09-18 06:46 UTC
Labels: bug
