### ISSUE TITLE
bug: cursor not display when input command

### ISSUE THREAD

**Issue by BanboLee** [LazyVim/LazyVim#2287] opened 2024-01-02 03:53 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

The cursor not displayed when i input command
![image](https://github.com/LazyVim/LazyVim/assets/18645045/51001194-240a-4159-bc05-adf0819331d0)

### Steps To Reproduce

1. open lazyvim
2. update all plugins
3. input command

### Expected Behavior

cursor should be show in input window

### Repro

```Lua
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
```

**Comment by dpetka2001** [comment] 2024-01-02 09:10
Can't reproduce with default LazyVim starter. Are you able to reproduce this with default LazyVim starter? Try the following
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Are you still not able to see the cursor?
Cleanup
```bash
rm -rf ~/.config/lazytest
rm -rf ~/.local/share/lazytest
rm -rf ~/.local/state/lazytest
rm -rf ~/.cache/lazytest
```

**Comment by BanboLee** [comment] 2024-01-02 13:44
> Can't reproduce with default LazyVim starter. Are you able to reproduce this with default LazyVim starter? Try the following
> 
> ```shell
> 1. `mkdir ~/.config/lazytest`
> 2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
> 3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
> 4. Restart Neovim with the command provided in step 3
> ```
> 
> Are you still not able to see the cursor? Cleanup
> 
> ```shell
> rm -rf ~/.config/lazytest
> rm -rf ~/.local/share/lazytest
> rm -rf ~/.local/state/lazytest
> rm -rf ~/.cache/lazytest
> ```

I can't reproduce too, may be other plugin make this issue.  Is there any way to find it?

**Comment by dpetka2001** [comment] 2024-01-02 14:47
Well, you would have to manually disable/enable them one by one and see which one causes the problem. You are the one who uses your own configuration. 

Since this isn't a LazyVim problem, kindly close this issue please.

**Comment by BanboLee** [comment] 2024-01-02 15:39
Thanks!

**Closed** 2024-01-02 15:39 UTC
Labels: bug
