### ISSUE TITLE
bug: bug: floating terminal affects the theme

### ISSUE THREAD

**Issue by LovesAsuna** [LazyVim/LazyVim#2872] opened 2024-03-29 06:40 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1999+g6f6abd8c0

### Operating system/version

MacOS 14.4.1

### Describe the bug

after I close the floating terminal, The background of nvim is still gray

### Steps To Reproduce

1. 
<img width="1920" alt="image" src="https://github.com/LazyVim/LazyVim/assets/32810896/32a98f54-2303-4d6c-957b-9450337d8424">
2. 
<img width="1920" alt="image" src="https://github.com/LazyVim/LazyVim/assets/32810896/3b4695f3-0cb6-4dcc-ba34-d44f4b6b2827">
3. 
<img width="1920" alt="image" src="https://github.com/LazyVim/LazyVim/assets/32810896/8dd02f9e-cf99-42c2-933a-b098abbc8675">

### Expected Behavior

The performance of lazyvim before update

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2024-03-29 06:52
Can you please update lazy.nvim and LAzyVim to see if that resolves it? I fixed some issues related to this over the last couple of days.

If not, how do you close the window?

**Comment by LovesAsuna** [comment] 2024-03-29 06:57
> Can you please update lazy.nvim and LAzyVim to see if that resolves it? I fixed some issues related to this over the last couple of days.
> 
> If not, how do you close the window?

It is the latest version，and I usually used the `exit` commond to close the window

**Comment by folke** [comment] 2024-03-29 07:19
I can't reproduce this with a clean LazyVim build.
And as I said the issue you are experiencing really looks like something that was fixed.

Again, make sure your `lazy.nvim` is up to date.

Closing, since it's not reproducible with the repro and instructions

**Closed by folke** 2024-03-29 07:19 UTC
Labels: bug

**Comment by LovesAsuna** [comment] 2024-03-29 07:46
This terminal windows is opened with `<Space>fT`

**Comment by LovesAsuna** [comment] 2024-03-29 08:17
I updated nvim to the latest dev version and it was fine. It should be a problem with nvim itself.
