### ISSUE TITLE
bug: Cursor always jumps after autoformatting(maybe caused by `conform.nvim`)

### ISSUE THREAD

**Issue by beyond-fu** [LazyVim/LazyVim#2042] opened 2023-11-19 13:48 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu22.04(XFCE) on x86-64(virtual machine)

### Describe the bug

Today I updated all my plugins. When I write `systemverilog` and save the file with auto-formatting, the cursor always jumps to the bottom/beginning or somewhere of the current file. And the same seems to be true of `undoing`. This affects me much. 

I tried to find the reason using `git bisect` and it seems to break starting from introducing `conform.nvim` as the lsp formatter(https://github.com/LazyVim/LazyVim/commit/4584410e76bf8a6ba426270bef8eca5a100d4cce). I don't know if this is my problem or the plugin itself.
> (One of the features of `conform.nvim` is "Most formatters replace the entire buffer, which clobbers extmarks and folds, and can cause the viewport and cursor to jump unexpectedly")

### Steps To Reproduce

Here is all my configs based on LazyVim.(https://github.com/beyond-fu/nvim_config/blob/master/lua/plugins/all_plugins.lua)

Thanks!

### Expected Behavior

The cursor should not move after saving and auto-formatting.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment] 2023-11-20 09:54
Hi @beyond-fu,

Looking at your config, I think `conform.nvim` is not used for formatting `systemverilog` files.

From your config, I extracted the following:

`repro.lua`:

```lua
-- Minimal `init.lua` to reproduce an issue. Save as `repro.lua` and run with `nvim -u repro.lua`

-- sets std paths to use .repro and bootstraps lazy
local function bootstrap(root) -- DO NOT change the paths
  for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
  end
  local lazypath = root .. "/plugins/lazy.nvim"
  if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
  end
  vim.opt.rtp:prepend(vim.env.LAZY or lazypath)
end
local root = vim.fn.fnamemodify("./.repro", ":p")
bootstrap(root)

-- recognize systemverilog
vim.api.nvim_create_autocmd({ "BufEnter", "BufAdd", "BufRead" }, {
  pattern = { "*.vh", "*.svh" },
  command = "set filetype=systemverilog",
})

-- install plugins
local plugins = {
  -- optional: reduce the number of plugins needed to reproduce the problem
  { "abeldekat/lazyflex.nvim", version = "*", import = "lazyflex.hook", opts = {} },

  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  {
    "neovim/nvim-lspconfig",
    opts = {
      -- manage integration of LSP and neovim(upper level, because of the existence of Mason)
      servers = {
        -- use veridian to dot-completion, syntax lint(slang and verible), veridian cannot hover define macro
        veridian = {
          cmd = { "veridian" },
          filetypes = { "systemverilog", "verilog" },
          -- root_dir = require("lspconfig.util").root_pattern("veridian.yml", ".git"),
          single_file_support = true,
        },
        -- use svlangserver to gd, formatting(verible), hover
        -- svlangserver hover has a bug, `define macro hover` will not work after saving current file.
        -- Must save the `define macro file` again to make `define macro hover` work again.
        svlangserver = {
          cmd = { "svlangserver" },
          filetypes = { "verilog", "systemverilog" },
          -- root_dir = require("lspconfig.util").root_pattern("veridian.yml", ".git"),
          settings = {
            systemverilog = {
              includeIndexing = { "*.{v,vh,sv,svh}", "**/*.{v,vh,sv,svh}" },
              disableLinting = true,
              disableCompletionProvider = true,
              disableHoverProvider = false,
              disableSignatureHelpProvider = true,
              -- linter = "verilator",
              -- cannot disable formatting for svlangserver, so do not format with veridian
              formatCommand = "verible-verilog-format --indentation_spaces=4",
            },
          },
          single_file_support = true,
        },
        setup = {
          veridian = function()
            require("lazyvim.util").lsp.on_attach(function(client, _)
              if client.name == "veridian" then
                -- disable hover of veridian
                client.server_capabilities.hoverProvider = false
              end
            end)
          end,
        },
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```


Unfortunately, on my arch system installing `veridian` is not trivial.

Could you test if the issue arises using this minimal config?

I added the `repro` to `~/.config/nvim/repro.lua` and copied an example systemverilog file from [this tutorial](https://www.chipverify.com/systemverilog/systemverilog-tutorial). That file is saved as `~/.config/nvim/db_top.sv`

**Comment by beyond-fu** [comment] 2023-11-21 15:23
Thanks for your reply!

First, I tried to set `enabled=false` just in my `all_plugins.lua`(like below) and no longer the cursor jumping.
```
{
   "stevearc/conform.nvim",
   enabled = false,
},
```

Second, I used your `repro.lua` to test, it turns out that the bug of cursor jumping remains. By the way it doesn't seem to matter if `veridian` is installed because I use `svlangserver` to format. I built it from source and I don't know if it is available for Arch. Note that the bug may not occur if your `.sv` file is too short.(I can provide a screen recording if you need.)

Finally, I tried `lazyflex.nvim`  using the configuration you mentioned in my `all_plugins.lua`, and the problem remains.

So these confused me. For now I think `conform.nvim` is to blame. And I wanna know what is the purpose of introducing `conform.nvim` to `LazyVim`, and which plugin does `conform.nvim` replace from before? Is it OK to disable it?

**Comment by abeldekat** [comment] 2023-11-21 17:45
Hi @beyond-fu,

`Conform.nvim` replaces `null-ls` in `LazyVim` specifically for formatting. The plugin is not related to the `lsp`.
The successor of `null-ls` is [`none-ls`](https://github.com/nvimtools/none-ls.nvim).
You can still use null-ls in the usual way by adding the following extra: `lazyvim.plugins.extra.lsp.none-ls`. 

Regarding my repro: 
I removed the `veridian` parts.
`:LazyFormatInfo` shows that `svlangserver` is the `formatter`. However, I have not been able to observe any formatting using file db_top.sv...). Note that I have no knowledge regarding `systemverilog` and did not install anything else.

The lsp is installed by mason: 

- https://github.com/imc-trading/svlangserver
- version 0.4.1

Do I understand correctly that you used the `repro` using file `db_top.sv` and the issue still remains?
If you used another file, could you share that file, in your github perhaps?

> Finally, I tried lazyflex.nvim using the configuration you mentioned in my all_plugins.lua, and the problem remains.

That's strange. I would expect only `lsp` and `treesitter` plugins enabled, and all other plugins including `conform.nvim` disabled.  Did you add `lazyflex` as indicated in the `readme`, as the first plugin in your `config.lazy.lua`?

File `db_top.sv`:

```systemverilog
module tb_top ();

	reg clk;
	reg resetn; 
	reg d;
	wire q;
	
	// Instantiate the design
	d_ff  d_ff0 (	.clk (clk),
		       		.resetn (resetn),
		       		.d (d),
		       		.q (q));
	
	// Create a clock
	always #10 clk <= ~clk;
	
	initial begin
		resetn <= 0;
		d <= 0;
		
		#10 resetn <= 1;
		#5      d <= 1;
		#8      d <= 0;
		#2      d <= 1;
		#10     d <= 0;
	end
endmodule
```

**Comment by abeldekat** [comment] 2023-11-21 19:35
> You have to also install verible from Mason to be able to observe formatting

Thanks!

> conform falls back to LSP formatting, since it's not configured with any formatter for SystemVerilog

Indeed. My previous comment is not correct:
> ... The plugin is not related to the lsp. ...

Formatting works with or without conform. The result is different though: 2 spaces for indentation instead of 4(using conform). No cursor jumping.

**Comment by abeldekat** [comment] 2023-11-21 19:50
... I do observe a difference when formatting, invoked when joining lines:

- with conform: indentation is two spaces
- without: indentation is four spaces

**Comment by dpetka2001** [comment] 2023-11-21 20:45
I don't observe that. The only place with 4 spaces is 
```
d_ff d_ff0 (
      .clk(clk),
      .resetn(resetn),
      .d(d),
      .q(q)
  );
```
The rest is 2 spaces either with `conform` enabled or disabled. It seems pretty consistent from what I can observe, although I don't know how it's supposed to format.

**Comment by beyond-fu** [comment] 2023-11-22 13:29
Hi, @abeldekat 
Sorry, my bad, I didn't read the README of `lazyflex.nvim` and now I found that it's a very useful plugin. And yes you need to install `verible` first.

After putting the config of `lazyflex` at first in `LazyVim` spec, there is no more cursor jumping. 

I added my `test.sv` to my `nvim_config repo`(https://github.com/beyond-fu/nvim_config), you can try it on your platform. Bottom is a video. Basically all I do is saveing the file(with auto-format).

By the way, is the `Autoformat autocmd` function now implemented by `conform.nvim` in `LazyVim`? I tried to read the source code of `LazyVim` but ... : (  

And will there be conflicts when `none-ls` and `conform` works together? So I need to config them exactly? From my perspective, they are all a bridge between my host computer and neovim.

I like some features of `conform.nvim` like `range formatting`, so I hope to resolve this problem.

 Thanks!

https://github.com/LazyVim/LazyVim/assets/54238106/a89d66b1-c29e-4340-a291-24e14da6a7ed

**Comment by dpetka2001** [comment] 2023-11-22 13:51
Can you add `formatting` to the lazyflex `presets` key? Do you observe any change in behavior? Would also be good if you tried with a fresh Lazyvim starter template and just installing `svlangserver` and `verible` without customizing anything else to ensure there's nothing wrong with your configuration.

**Comment by beyond-fu** [comment] 2023-11-22 15:09
Hi @dpetka2001 
I added the `formatting` into `presets option`. When `veridian` is enabled this problem remains, otherwise there is no more jumping.

And I tried `nvim -u repro.lua ./test.sv` with just `lua_ls` and `svlangserver` installed, same result. As long as `veridian` is enabled cursor jumping occurs. 

I think it's very very strange, because if I set `enabled=false` for `conform.nvim` then no more jumping : (  I don't know either `conform.nvim` or `veridian LSP` is to blame.

Unfortunately, I need to use `veridian` to finish some work, because there is no fully functional LSP for verilog/systemverilog !!!

**Comment by dpetka2001** [comment] 2023-11-22 15:30
Is `veridian` different from `svlangserver`? It's not installed by Mason?

**Comment by beyond-fu** [comment] 2023-11-22 15:59
No, they are different. I installed `veridian` from source not by `Mason`. It only supports installing from release/source, but it gives the configuration for neovim built-in LSP client(https://github.com/vivekmalneedi/veridian/wiki/Usage-Instructions-for-various-LSP-Clients). I wrote the differences between the two LSP in my `all_plugins.lua`

**Comment by dpetka2001** [comment] 2023-11-22 16:05
Ok, so you have 2 different servers formatting. Maybe that's the slip up you observe in the rapid cursor motions? Do you need both of them formatting? Although, I don't see any direct setting for disabling `svlangserver` formatting. Maybe try in your `veridian.yml` to disable formatting, since it provides such an option?

**Comment by abeldekat** [comment] 2023-11-22 19:02
Using the test file in your github repo, I can reproduce when only systemverilog is present as `lsp`. 
Customized repro:

```
local function bootstrap(root) -- DO NOT change the paths
  for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
  end
  local lazypath = root .. "/plugins/lazy.nvim"
  if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
  end
  vim.opt.rtp:prepend(vim.env.LAZY or lazypath)
end
local root = vim.fn.fnamemodify("./.repro", ":p")
bootstrap(root)

-- recognize systemverilog
vim.api.nvim_create_autocmd({ "BufEnter", "BufAdd", "BufRead" }, {
  pattern = { "*.vh", "*.svh" },
  command = "set filetype=systemverilog",
})

local plugins = {
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  { "mason.nvim", opts = { ensure_installed = { "verible" }}},
  {
    "neovim/nvim-lspconfig",
    opts = {
      -- manage integration of LSP and neovim(upper level, because of the existence of Mason)
      servers = {
        -- use svlangserver to gd, formatting(verible), hover
        -- svlangserver hover has a bug, `define macro hover` will not work after saving current file.
        -- Must save the `define macro file` again to make `define macro hover` work again.
        svlangserver = {
          cmd = { "svlangserver" },
          filetypes = { "verilog", "systemverilog" },
          -- root_dir = require("lspconfig.util").root_pattern("veridian.yml", ".git"),
          settings = {
            systemverilog = {
              includeIndexing = { "*.{v,vh,sv,svh}", "**/*.{v,vh,sv,svh}" },
              disableLinting = true,
              disableCompletionProvider = true,
              disableHoverProvider = false,
              disableSignatureHelpProvider = true,
              -- linter = "verilator",
              -- cannot disable formatting for svlangserver, so do not format with veridian
              formatCommand = "verible-verilog-format --indentation_spaces=4",
            },
          },
          single_file_support = true,
        },
      },
    },
  },
  { "conform.nvim", cond = true },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

With conform.nvim enabled, the file is formatted with an indentation level of 2.
When conform.nvim is disabled, your 4 space indentation level is preserved.

When I change the formatCommand, the cursor jumping is not happening anymore:

```
-- formatCommand = "verible-verilog-format --indentation_spaces=4",
formatCommand = "verible-verilog-format",
```

**Comment by dpetka2001** [comment] 2023-11-22 19:44
I can't reproduce this with the latest `repro.lua` and the `test.sv` from OP's repo. For me it always formats according to what the `formatCommand` is set to even with `conform` enabled. Either 2 spaces or 4 spaces. Also I don't observe any cursor jumps even with `formatCommand = "verible-verilog-format --indentation_spaces=4",`

**Comment by abeldekat** [comment] 2023-11-22 19:44
> And will there be conflicts when none-ls and conform works together? So I need to config them exactly? From my perspective, they are all a bridge between my host computer and neovim.

You can use the plugins together if you enable extra `lazyvim.plugins.extras.lsp.none-ls`.

**Comment by beyond-fu** [comment] 2023-11-23 05:27
Hi, @dpetka2001 @abeldekat 

I think I find the reason of cursor jumping for your new `repro.lua` and my configurations. All the reason is there are two active formatters for current one buffer.

First, I tried your new `repro.lua`, indeed cursor jumping occurs. But for me, I installed `verible` from release not from `Mason` in neovim. So if you do so and delete this line `{ "mason.nvim", opts = { ensure_installed = { "verible" }}},` , the `svlangserver` will format successfully, however, no cursor jumping. I think it's because neovim cannot recognize the LSP installed in host rather than in `mason`.(i.e. no `verible` in `LspInfo/LazyFormatInfo/ConformInfo` window).

Then for the `veridian`, I usually have a `veridian.yml` under my project, like this. 
```
include_dirs:
  - rtl/
source_dirs:
  - rtl/
auto_search_workdir: true
verible:
  syntax:
    enabled: true
    path: "verible-verilog-syntax"
  format:
    enabled: false
```
Because `svlangserver` does not have an option to disable `verible's formatter`, so I use `svlangserver` to format while setting `enabled=false` for `veridian's formatting functinon(also powerd by verible)`. But, I found that disabling formatting for `veridian` actually didn't work! It still formats even when disabling the formatting function of `veridian` and the whole `svlangserver` LSP. So actually there are two active formatters for one buffer at the same time. Even more, they all use `verible-verilog-format`, so god knows what will happen.

I originally thought that `svlangserver` doesn't support to disable formatting because of no explicit `disable option`. But I found that setting `formatCommand = ""` for `svlangserver` did work. So now I solved this problem by disabling `svlangserver's formatting` and enabling `veridian's formatting`.

So I and the `veridian LSP` should be to blame. After all, normally nobody uses two formatter for one buffer.
I think I should close this issue?

Thank both of you!

**Comment by dpetka2001** [comment] 2023-11-23 08:43
Glad you were able to solve it. I believe you should close it if there's not anything else that you have trouble with.

**Comment by abeldekat** [comment] 2023-11-23 09:57
You're welcome! I agree with @dpetka2001.

**Closed** 2023-11-23 10:28 UTC
Labels: bug

**Comment by abeldekat** [comment] 2023-11-24 19:40
Fyi: I created the following issue: https://github.com/stevearc/conform.nvim/issues/215
