### ISSUE TITLE
bug: lsp error message on opening new buffer

### ISSUE THREAD

**Issue by pmelab** [LazyVim/LazyVim#1515] opened 2023-09-28 13:18 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

MacOS 13.5.1

### Describe the bug

After opening a couple of files, i'm constantly getting this notification for every file i'm opening that has a language server attached to it.

```
Failed to run client.before_init for settings/plugins/lspconfig
vim/shared.lua:0: Cannot deepcopy object of type userdata

stack traceback:
	vim/shared.lua: in function 'deepcopy'
	vim/shared.lua: in function 'deepcopy'
	vim/shared.lua: in function 'deepcopy'
	vim/shared.lua: in function 'deepcopy'
	vim/shared.lua: in function 'deepcopy'
	...nvim/lazy/neoconf.nvim/lua/neoconf/plugins/lspconfig.lua:44: in function 'on_config'
	....local/share/nvim/lazy/neoconf.nvim/lua/neoconf/util.lua:47: in function <....local/share/nvim/lazy/neoconf.nvim/lua/neoconf/util.lua:46>
	[C]: in function 'func'
	...al/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/util.lua:54: in function 'func'
	...al/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/util.lua:54: in function <...al/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/util.lua:52>
	[C]: in function 'pcall'
	...share/nvim/lazy/nvim-lspconfig/lua/lspconfig/configs.lua:201: in function 'make_config'
	...share/nvim/lazy/nvim-lspconfig/lua/lspconfig/manager.lua:203: in function 'add'
	...share/nvim/lazy/nvim-lspconfig/lua/lspconfig/manager.lua:277: in function <...share/nvim/lazy/nvim-lspconfig/lua/lspconfig/manager.lua:266>
	[C]: in function 'pcall'
	...l/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/async.lua:5: in function <...l/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/async.lua:4>
```

It does not seem to do anything, but it is very annoying.

When I run `:LspRestart` the notification will appear _a lot_ of times. I suppose for each language server.
There is nothing in the lsp logs.

### Steps To Reproduce

It does not happen with a unchanged install of LazyVim, but as soon as i uncomment any extra spec in `lazy.lua`, eg. typescript or json.
The more language servers are installed, the sooner the error appears (less files to open until it happens).
It also does not happen in all of my projects, but I was not able to derive a pattern.
I am fully aware that this is probably not enough information to pinpoint the problem, but I was hoping for suggestions where I could continue to dig.

### Expected Behavior

The notificaton does not appear.

**Comment by folke** [comment] 2023-09-28 14:54
Are you the same user that posted this? https://www.reddit.com/r/neovim/comments/16uazit/failed_to_run_clientbefore_init_for/

Do you know what lsp server is causing this?

Did you add any other plugins besides the extras?

**Comment by pmelab** [comment] 2023-09-28 15:09
When testing individual plugins I also cleared `~/.local/share/nvim` and `~/.local/state/nvim`. Adding either `{ import = "lazyvim.plugins.extras.lang.typescript" }` *or* `{ import = "lazyvim.plugins.extras.lang.json" }` causes the error to appear.

**Comment by folke** [comment] 2023-09-28 15:48
That's even weirder. Then it would mean there's a userdata value somewhere nested inside the client's settings object.
That makes no sense...

Do let me know if you'd find a way to reproduce this, since I can't

**Comment by Memnoc** [comment] 2023-09-28 16:01
@folke is it possible that some of these updates generated a conflict somewhere along the line of 

```
Failed to run `config` for indent-blankline.nvim

...e/nvim/lazy/indent-blankline.nvim/lua/ibl/highlights.lua:18: attempt to call field 'nvim_get_hl' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/highlights.lua:18 _in_ **get**
  - /indent-blankline.nvim/lua/ibl/highlights.lua:26 _in_ **setup_builtin_hl_groups**
  - /indent-blankline.nvim/lua/ibl/highlights.lua:52 _in_ **setup**
  - /indent-blankline.nvim/lua/ibl/init.lua:44 _in_ **setup**
  - /indent-blankline.nvim/lua/ibl/init.lua:59 _in_ **setup**
  - /telescope.nvim/lua/telescope/actions/set.lua:168 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **run_replace_or_original**
  - /telescope.nvim/lua/telescope/actions/mt.lua:65 _in_ **key_func**
  - /telescope.nvim/lua/telescope/mappings.lua:350 _in_ **execute_keymap**
```
20 minutes ago was all good, I have stopped to add a plugin, and at restart I got this - uninstalling the plugin does not get rid of the error. It seems that the indent-blankline is also working weirdly - I do not have all the guides visible by default, only when I hover over some JSX.
This is the plug in, I have been using it for a while on another machine with the same config and never had any issues: https://github.com/ziontee113/icon-picker.nvim

**Comment by folke** [comment] 2023-09-28 16:03
@Memnoc no, that is not related to this issue. indent blankline released v3 of their plugin. Your NEovim version seems to be too old.

**Comment by folke** [comment] 2023-09-28 21:05
That still doesn't explain why that would give an error. Can you share the files under that `.vscode` folder by any chance?

**Comment by pmelab** [comment] 2023-09-29 03:49
Sure. It started with this `settings.json`:
```
{
  "npm.packageManager": "pnpm",
  "eslint.format.enable": true,
  "eslint.codeActionsOnSave.rules": null,
  "editor.formatOnSave": true,
  "rest-client.followredirect": false,
  "deno.enable": true,
  "deno.unstable": true,
  "deno.enablePaths": ["./apps/website/netlify/edge-functions"],
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.tabSize": 2,
  "vitest.include": [
    "**/src/**/*.test.{ts,tsx}"
  ],
  "vitest.enable": true,
  "vitest.changeBackgroundColor": true,
  "files.associations": {
    "*.module": "php",
    "*.install": "php",
    "*.profile": "php"
  }
}
```

**Comment by pmelab** [comment] 2023-09-29 03:59
More specifically: `  "eslint.codeActionsOnSave.rules": null,` seems to be the culprit. And it seems to be a misconfiguration. The respective option should be either "all" or "problems". Not sure how `null` got in there.

**Comment by folke** [comment] 2023-09-29 09:11
@pmelab great, was able to reproduce this and fix it.

The error should no longer show after updating neoconf. Closing

**Closed by folke** 2023-09-29 09:11 UTC
Labels: bug
