### ISSUE TITLE
bug: can't create backup at random time on tex files

### ISSUE THREAD

**Issue by Nora-n** [LazyVim/LazyVim#1608] opened 2023-10-06 22:49 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

6.4.12-arch1-1

### Describe the bug

I've been editing and compiling LaTeX files using LazyVim and Vimtex for over a year. Since a few days, I have errors randomly popping up whenever I want to save "too quickly", *when I have a split window showing at least 2 buffers*, with an error message `return require'lazyvim.util.ui'.statuscolumn(...)_check_callback[4]..vimtex#compiler#callback[54]..vimtex#qf#open[4]..vimtex#qf#setqflist[31]..vimtex#qf#bibtex#addqflist[4]..234, line 2`, or `return nvim_bufferline(...).ui'.statuscolumn(...)_check_callback[4]..vimtex#compiler#callback[54]..vimtex#qf#open[4]..vimtex#qf#setqflist[31]..vimtex#qf#bibtex#addqflist[4]..238, line 2`, or even sometimes `return require'lazyvim.util.ui'.statuscolumn(...)13]..vimtex#parser#toc#parse, line 78`.

By "too quickly", I mean that if I wait long enough (5 to 10 seconds), I can save alright.

This error is actually hiding a prompt, asking me a `y/n` question that I can't read unless I type on another key. Typing `n` doesn't save. Typing `y` tries to save, but gives the error message `E509: Cannot create backup file (add ! to override)`. This also creates a copy of said file in my root git directory. Writing with `!` does write, but the compilation doesn't work on that file anymore?

I checked the `backupdir` with `:se backup? backupdir?`, which was setup to `backupdir=~/.local/state/nvim/backup//`, and added the following lines in my `init.lua`:
```lua
-- set undo and backup
local prefix = vim.fn.expand("~/.local/state/nvim")
vim.opt.undodir = { prefix .. "/undo/" }
vim.opt.backupdir = { prefix .. "/backup/" }
vim.opt.directory = { prefix .. "/swap/" }
```
All of my previous backups, undo and swap were indeed already in these folders, and this change did nothing.

If I have no other buffer opened, this doesn't seem to arise.

This isn't a clear issue because I can't get where it lies: is it vimtex, is it lazyvim… sorry for the mess.

I unfortunately couldn't reproduce the issue with the minimal `repro.lua`.

### Steps To Reproduce

1. Open a .tex file.
2. Edit, compile without issue.
3. Save a few times.
4. Error happens.

### Expected Behavior

I expect the saving to work and not be pushed on another file in my root git directory.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  "lervag/vimtex",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment] 2023-10-07 09:54
I've noticed a similar issue with `y/foo`. Seems to be triggered by Noice and the custom statuscolumn.
I'm suspecting there's a bug in Neovim that overwrites memory somewhere when it shouldn't.

Will look into it.

**Comment by folke** [comment] 2023-10-07 09:55
Can you do `:Noice disable` and confirm that no longer triggers the issue?
And also with `:set statuscolumn=` and again confirm the issue is gone.

**Comment by folke** [comment] 2023-10-07 11:55
Can't reroduce your issue. What is your vimtex config?

**Comment by folke** [comment] 2023-10-07 11:58
I just pushed an update to noice that works around a similar issue I had. 
This will likely not fix your issue, so I need more input.

**Comment by folke** [comment] 2023-10-08 21:04
I'll assume this also fixed your issue. If not, submit an issue in the noice.nvim repo with the exact steps to reproduce.
Closing...

**Closed by folke** 2023-10-08 21:04 UTC
Labels: bug

**Comment by Nora-n** [comment] 2023-10-11 19:01
Hi,

Thanks for the time you took concerning this issue. I apologize for not being able to answer sooner.

`:Noice disable` helped a lot; I sometimes stumble on a `File has changed since reading it!!!` warning, but typing `n` and saving right afterwards works. By precaution, I tested `set statuscolumn=` too, I'm not so sure about the impact of this for the time being.

You're right in considering this issue closed, it doesn't belong to this project. I'm glad you were able to find the main issue nonetheless!
