### ISSUE TITLE
bug: Error when launching my LazyVim

### ISSUE THREAD

**Issue by Estrella-Explore** [LazyVim/LazyVim#2063] opened 2023-11-25 11:16 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 22.04

### Describe the bug

I got this error prompt when I was launching my vim,
and I don't know how to deal with it.
```
Error detected while processing /home/explore/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/explore/.config/nvim/lua/config/lazy.lua:9: module 'lazy' no
t found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/usr/share/luajit-2.1.0-beta3/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/usr/share/lua/5.1/lazy.lua'
        no file '/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/explore/.config/nvim/lua/config/lazy.lua:9: in main chunk
        [C]: in function 'require'
        /home/explore/.config/nvim/init.lua:2: in main chunk
Press ENTER or type command to continue
```
(For sure, continuing to use cannot load LazyVim, just a normal NeoVim.)

### Steps To Reproduce

*1. Prepare a clear and new Ubuntu 22.04 environment.*

*2. Try `sudo apt install neovim` to install it.*
and
``` bash 
git clone https://github.com/LazyVim/starter ~/.config/nvim
``` 

*3. Launch `nvim`.*

### Expected Behavior

It should just like:

![213447056-92290767-ea16-430c-8727-ce994c93e9cc](https://user-images.githubusercontent.com/292349/213447056-92290767-ea16-430c-8727-ce994c93e9cc.png)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment] 2023-11-25 11:30
It's stated under [Requirements](https://www.lazyvim.org/#%EF%B8%8F-requirements) that Neovim should be at least version 0.9.0. Try to install a newer version of Neovim.

**Comment by Estrella-Explore** [comment] 2023-11-25 13:18
> It's stated under [Requirements](https://www.lazyvim.org/#%EF%B8%8F-requirements) that Neovim should be at least version 0.9.0. Try to install a newer version of Neovim.
> 
> Edit: also from your error it seems that `lazy.nvim` installation didn't finish properly? You could try deleting `~/.local/share/nvim/lazy/lazy.nvim` directory and open Neovim again for the installation to hopefully finish properly this time.

err,I don't know why, but that's the newest version in my apt source...
embrassing...

**Comment by dpetka2001** [comment] 2023-11-25 13:21
You can check other ways of [installing](https://github.com/neovim/neovim#install-from-package) Neovim and I would also suggest (from my personal experience) to also give [bob](https://github.com/MordechaiHadad/bob) a try, which is a cross-platform tool for installing Neovim.

**Comment by dpetka2001** [comment] 2023-11-30 09:07
@Estrella-Explore Would you please close this issue if your problem is resolved?

**Closed** 2023-11-30 19:19 UTC
Labels: bug

**Comment by furtrade** [comment] 2023-12-01 01:36
Was the issue resolved? I have the exact same problem even though I have the latest nvim. How did this issue get resolved?

**Comment by dpsi9** [comment] 2024-01-06 15:29
@furtrade you can first try to delete ~/.local/share/nvim/lazy directory then delete the ~/.config file then reinstall the lazyvim setup it will work

**Comment by Estrella-Explore** [comment] 2024-01-07 07:47
Thank you for helping
________________________________
发件人: Dipendra Pratap Singh ***@***.***>
发送时间: 2024年1月6日 23:29
收件人: LazyVim/LazyVim ***@***.***>
抄送: Estrella-Explore ***@***.***>; Mention ***@***.***>
主题: Re: [LazyVim/LazyVim] bug: Error when launching my LazyVim (Issue #2063)


@furtrade<https://github.com/furtrade> you can first try to delete ~/.local/share/nvim/lazy directory then delete the ~/.config file then reinstall the lazyvim setup it will work

―

**Comment by frankievalentine** [comment] 2024-01-23 22:17
I had this error as well. After installing Neovim with Homebrew I reached some permissions error when cloning the LazyVim repo into my .config folder. The errors showed that the plugins could not be created in my .local/share folder. I attempted changing permissions on /usr/local, .local, and .config. Nothing worked. When I cloned the repo to my .local/share folder everything works.

So... `sudo git clone https://github.com/LazyVim/starter ~/.local/share/nvim`

**Comment by Estrella-Explore** [comment] 2024-01-24 05:32
Ahhaaa, thanks for your solution, everything works now 😊

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Frankie ***@***.***>
发送时间: Wednesday, January 24, 2024 6:17:55 AM
收件人: LazyVim/LazyVim ***@***.***>
抄送: Estrella-Explore ***@***.***>; Mention ***@***.***>
主题: Re: [LazyVim/LazyVim] bug: Error when launching my LazyVim (Issue #2063)


I had this error as well. After installing Neovim with Homebrew I reached some permissions error when cloning the LazyVim repo into my .config folder. The errors showed that the plugins could not be created in my .local/share folder. I attempted changing permissions on /usr/local, .local, and .config. Nothing worked. When I cloned the repo to my .local/share folder everything works.

So... sudo git clone https://github.com/LazyVim/starter ~/.local/share/nvim

**Comment by KaBach** [comment] 2024-01-26 09:16
I have just encountered the same Problem. Nvim + Lazy works fine on my local machine and on an HPC, however on another HPC it fails with the exact same config files. I then followed the exact same steps from https://www.lazyvim.org/installation and still get the following error message:

```
Error detected while processing /gstore/home/bachk1/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /gstore/home/bachk1/.config/nvim/lua/config/lazy.lua:9: module 'lazy' not found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /gstore/home/bachk1/.config/nvim/lua/config/lazy.lua:9: in main chunk
        [C]: in function 'require'
        /gstore/home/bachk1/.config/nvim/init.lua:2: in main chunk
```

nvim version:
`NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794`

Any help would be appreciated!

**Comment by dpetka2001** [comment] 2024-01-26 10:00
Delete `~/.local/share/nvim/lazy` directory. Something must have gone wrong during the `git clone` operation of the repo. Do you have permissions to write in that directory?

**Comment by KaBach** [comment] 2024-01-26 10:24
Hey,
thanks for the quick reply. I did do this before, following the steps from the installation : 

> # optional but recommended
> mv ~/.local/share/nvim{,.bak}
> mv ~/.local/state/nvim{,.bak}
> mv ~/.cache/nvim{,.bak}

And I do have write permissions in all three directories.

**Comment by dpetka2001** [comment] 2024-01-26 10:30
Delete the directory I mentioned in my previous post and open Neovim. It should clone the `lazy.nvim` repo from start. Something must have gone wrong during the `git clone` operation.

**Comment by KaBach** [comment] 2024-01-26 10:35
Ah fantastic the git verison solved it. Dind't realize I had a very old version of git on that HPC, just upgraded and everything works. Thanks so much for the fast help!

**Comment by dpetka2001** [comment] 2024-02-19 21:31
How did you install Neovim?

**Comment by ouyama-sa** [comment] 2024-02-19 23:34
I installed though my package manager, portage on Gentoo, with no of the extra flags enabled besides **luajit** which is explicitly required for LazyVim. [Here](https://packages.gentoo.org/packages/app-editors/neovim) is the package page.

**Comment by dpetka2001** [comment] 2024-02-20 00:10
Uninstall it and try to install it via [bob](https://github.com/MordechaiHadad/bob) and test the behavior again.

**Comment by ouyama-sa** [comment] 2024-02-20 15:32
Sorry, I did not see you response. I managed to install it now. 
After some webscrapping I tweaked my .gitconfig like this:
``` 
~/.gitconfig

[url "git@github.com:"]
        insteadOf = https://github.com/
```
After that, I again removed both the `~/.config/nvim` _and_ the `~/.local/share/nvim` directories. Then manually cloned them both:
`git clone https://github.com/LazyVim/starter ~/.config/nvim`
then:
`git clone --filter=blob:none https://github.com/folke/lazy.nvim.git --branch=stable ~/.local/share/nvim`

After that, LazyVim was installed, I had some trouble with TreeSitter after that and it was resolved, but it is out of the scope of this issue. 

I do not think the problem was my package manager but git and probably my lack of correct configuration. 

Thanks for the help.

**Comment by zestzero** [comment] 2024-05-02 19:38
For my case, I have an old version of `git`. It was 2.15.0 so I just updated it to `2.45.0` and then it started to work.

**Comment by kapral18** [comment] 2024-06-02 07:22
@dpetka2001 I have latest version of git, I have removed cache, state, share folders that includes lazy folder. I see the same error, I also see another no module found error with osv when enabling dap.nlua extra and trying to launch it.

![image](https://github.com/LazyVim/LazyVim/assets/1625373/c28b7fae-372d-497e-a287-d685aef00c6c)
![image](https://github.com/LazyVim/LazyVim/assets/1625373/0e850443-8e5c-4594-9df9-b1fa1d38e961)

**Comment by folke** [comment] 2024-06-02 07:41
@kapral18 can you try with Neovim 0.10 stable instead of nightly?

**Comment by folke** [comment] 2024-06-02 07:42
Unlikely, but may be related to https://github.com/neovim/neovim/commit/dcdefd042840c7a6db5dce2963ac23c45a5287da

**Comment by dpetka2001** [comment] 2024-06-02 07:55
Maybe also check if something wrong with your gitconfig? Try to comment out everything in your global gitconfig and try installing again.

**Comment by kapral18** [comment] 2024-06-02 10:56
@folke I am installing via brew install neovim, which afaik installs stable unless --HEAD is specified. I reinstalled - no changes.

@dpetka2001 I haven't changed my gitconfig, so why would it have any affect? It was the same gitconfig when it was working. But anyways I commented out and still no effect.

**Comment by folke** [comment] 2024-06-02 11:01
Can you the contents of the file where you load lazy?

**Comment by kapral18** [comment] 2024-06-02 11:03
@folke 

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not (vim.uv or vim.loop).fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "plugins" },
  },
  change_detection = { enabled = false, notify = false },
  concurrency = 100,
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioninG,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  checker = { enabled = true }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```

**Comment by folke** [comment] 2024-06-02 11:05
Ok you probably have vim.env.LAZY set in your terminal

**Comment by folke** [comment] 2024-06-02 11:08
before launching neovim what does `echo $LAZY` show?

**Comment by kapral18** [comment] 2024-06-02 11:09
well I don't explicitly assign it anywhere in my dotfiles https://github.com/search?q=repo:kapral18/dotfiles+%22LAZY+%3D%22&type=code,

and I don't have it in my session `echo $LAZY` shows nothing as expected

**Comment by kapral18** [comment] 2024-06-02 11:09
![image](https://github.com/LazyVim/LazyVim/assets/1625373/0259ac28-cd47-498f-b69a-8aaaae7faffc)

**Comment by folke** [comment] 2024-06-02 11:50
Do a `print(lazypath)` before that require lazy. That folder is messed up I guess

**Comment by kapral18** [comment] 2024-06-02 11:59
@folke well I do reproduce this with vanilla lazyvim-starter as I said in the intro:

Check here https://github.com/kapral18/dotfiles/blob/ecb99b5c68a8f2c02ad0acb6573a097f5783447a/home/dot_config/exact_nvim/init.lua

> Do a print(lazypath) before that require lazy. That folder is messed up I guess

```lua
/Users/kapral18/.local/share/nvim/lazy/lazy.nvim
```
as expected

**Comment by kapral18** [comment] 2024-06-02 12:00
but here is the thing I just tested with your docker shortcut in installation section and it lazygit works fine, BUT if I comment out all my plugins in my lazyvim starter I still see the error

**Comment by kapral18** [comment] 2024-06-02 12:00
I just noticed the difference, in docker version luajit differs from my luajit mine is more recent

**Comment by kapral18** [comment] 2024-06-02 12:03
mine: 
![image](https://github.com/LazyVim/LazyVim/assets/1625373/8380607c-cfa1-4052-b1b9-9b4a9fcf8370)

in docker:
![image](https://github.com/LazyVim/LazyVim/assets/1625373/12b74975-3722-4e99-90bb-5198674d9240)

**Comment by dpetka2001** [comment] 2024-06-02 12:25
What are you doing exactly? Are you cloning the LazyVim starter yourself? Are you restoring your personal files from chezmoi?

**Comment by dpetka2001** [comment] 2024-06-02 12:26
If you do
```bash
1. `mkdir ~/.config/lazytest`
2. `git clone https://github.com/LazyVim/starter ~/.config/lazytest`
3. `NVIM_APPNAME=lazytest nvim` and wait for the installation to complete
4. Restart Neovim with the command provided in step 3
```
Does it install correctly?

**Comment by DrummyFloyd** [comment] 2024-06-02 12:31
i have the same issue , when i trie to commit with lazygit inside nvim , but when i try oustide it work without the error message

**Comment by folke** [comment] 2024-06-02 12:47
What does this have to do with lazygit? I don't follow

**Comment by DrummyFloyd** [comment] 2024-06-02 12:51
> ok, I do follow and know what's causing this,. In your config/lazy.lua remove the vim.env.LAZY or part

ok i removed that and work as before, but what introduced this issue ? was not there before ?=)

thank you @folke

**Comment by kapral18** [comment] 2024-06-02 13:18
@folke everything is fixed thanks

**Comment by kapral18** [comment] 2024-06-02 13:20
it's unclear tho how was `osv` affected why it got fixed with the same fix :)

**Comment by folke** [comment] 2024-06-02 14:33
osv also spawns a new neovim instance, so same issue
