### ISSUE TITLE
remap caps lock key to function as an escape key in lazyvim?

### ISSUE THREAD

**Issue by centuryhopper** [LazyVim/LazyVim#2380] opened 2024-01-18 14:35 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Arch Linux x86_64

### Describe the bug

I saw another person ask mapping jj to escape and the working answer was vim.keymap.set("i", "jj", "< ESC >", { silent = true }). However how to do this for caps lock? The docs do not tell you what their caps lock key is, which left me guessing: < CAPS > doesn't work < CAPSLOCK > doesn't work either...

### Steps To Reproduce

n/a

### Expected Behavior

n/a

**Comment by dpetka2001** [comment] 2024-01-18 14:58
Not a bug, better close this and ask in Discussions instead.

**Comment by dpetka2001** [comment] 2024-01-18 15:23
Also it seems (from the little google search I did) that this is not possible from inside Neovim itself. This [thread](https://unix.stackexchange.com/questions/165477/how-to-use-capslock-instead-of-escape-in-vim) discusses this and it seems you have to do the remap from your OS itself.

**Comment by cerebrl** [comment] 2024-01-18 20:16
That's correct. Not all key activation gets passed all the way down to the sub-process level. Some keys get caught by the OS, like Capslock, some get caught by the terminal, like Command. Even the official Alt/Option keypress can get caught or modified by the OS, like Mac.

**Comment by centuryhopper** [comment] 2024-01-18 20:19
Okay I will try that thread out. And report back here on the good news. I'll close this thread.

**Closed** 2024-01-18 20:19 UTC
Labels: bug

**Comment by centuryhopper** [comment] 2024-01-19 16:48
UPDATE:

I asked in the neovim subreddit and indeed it needs to be done systemwide. I am on arch linux hyprland, and found a working solution in the second reddit link. Good luck to anyone trying to make this swap. You have to do it systemwide at the time of this writing.

https://www.reddit.com/r/neovim/comments/199qy60/remap_caps_lock_key_to_function_as_an_escape_key/

https://www.reddit.com/r/hyprland/comments/13fqqfw/how_to_swap_the_esc_and_caps_lock_keys/
