### ISSUE TITLE
bug: I just updated LazyVim and I am getting indent-blankline.lua error

### ISSUE THREAD

**Issue by monoira** [LazyVim/LazyVim#3205] opened 2024-05-17 17:19 UTC
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

EndeavourOS Linux x86_64

### Describe the bug

I just updated lazyvim and now I am getting this error anytime I open any file:

```lua
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:428: attempt to call field 'iter' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:428 _in_ **tbl_join**
  - /indent-blankline.nvim/lua/ibl/config.lua:253 _in_ **merge_configs**
  - /indent-blankline.nvim/lua/ibl/config.lua:276 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - /LazyVim/lua/lazyvim/util/news.lua:77 _in_ **open**
  - /LazyVim/lua/lazyvim/util/news.lua:37 _in_ **lazyvim**
  - /LazyVim/lua/lazyvim/util/news.lua:20
```lua


I Have tried clean install with ~/.config/nvim ~/.cache/nvim ~/.local/share/nvim removed. still getting same thing with completely clean install too.

I have also tried installing `mini.indentscope`  extra but still get same error.

my neovim dotfiles: https://github.com/monoira/.dotfiles/tree/main/nvim

### Steps To Reproduce

Update lazyvim.

### Expected Behavior

I expected everything to go well...

### Repro

_No response_

**Comment by dpetka2001** [comment] 2024-05-17 17:21
Duplicate of #3192.

**Closed** 2024-05-17 17:42 UTC
Labels: bug
